### ISSUE TITLE
Markdown extension does not work with pdflatex when -output-dir option is set

### ISSUE THREAD

**Issue by dteod** [Witiko/markdown#105]
Hello,
First of all thank you for your work. 
The markdown package works out of the box but somehow fails when with pdflatex when the -output-dir option is set. 

Here are the steps to reproduce the problem.

Tree:
```
example
├── build/
└── main.tex
```

main.tex
``` latex
\documentclass{article}
\usepackage{markdown}

\begin{document}
\begin{markdown}
Here is my markdown text
\end{markdown}
\end{document}
```

When compiling with `pdflatex --shell-escape main.tex` the PDF comes out fine, but the command fills my folder with a lot of intermediate garbage files, so I wish to put these files in the `build` directory.

The command then becomes `pdflatex --shell-escape --output-directory=build main.tex`, but at that point I find myself with this tree:
```
example
├── build/
│   ├── main.aux
│   ├── main.log
│   ├── main.markdown.in
│   ├── main.markdown.lua
│   └── main.pdf
├── main.markdown.out
└── main.tex
```
In the `main.markdown.out` file the only content will be "Script file ./main.markdown.lua not found" and that is the actual text found in the PDF.

Is there a way to solve this issue?
Best regards,

Domenico

**Comment by dteod** [comment]
Eventually I managed to solve the issue editing the following line from where my package manager installed the package, in /usr/share/texmf-dist/tex/generic/markdown/markdown.tex:

*** /usr/share/texmf-dist/tex/generic/markdown/markdown.tex   2021-10-10 21:17:53.540887348 +0200
--- /usr/share/texmf-dist/tex/generic/markdown/markdown.tex     2021-10-10 21:15:22.981283692 +0200
***************
*** 55,61 ****
  \def\markdownOptionInputTempFileName{\jobname.markdown.in}%
  \def\markdownOptionOutputTempFileName{\jobname.markdown.out}%
  \def\markdownOptionErrorTempFileName{\jobname.markdown.err}%
! \def\markdownOptionOutputDir{.}%
  \def\markdownOptionCacheDir{\markdownOptionOutputDir/_markdown_\jobname}%
  \def\markdownOptionFrozenCacheFileName{\markdownOptionCacheDir/frozenCache.tex}
  \let\markdownOptionBlankBeforeBlockquote\undefined
--- 55,61 ----
  \def\markdownOptionInputTempFileName{\jobname.markdown.in}%
  \def\markdownOptionOutputTempFileName{\jobname.markdown.out}%
  \def\markdownOptionErrorTempFileName{\jobname.markdown.err}%
! \def\markdownOptionOutputDir{build}%
  \def\markdownOptionCacheDir{\markdownOptionOutputDir/_markdown_\jobname}%
  \def\markdownOptionFrozenCacheFileName{\markdownOptionCacheDir/frozenCache.tex}
  \let\markdownOptionBlankBeforeBlockquote\undefined

but I don't like it to be hardcoded this way, is there a way to retrieve the output directory directly?

**Comment by dteod** [comment]
At the beginning I found the extension via overleaf, after the problem arised I tried looking at the technical documentation doing a research on the "outputdir", "output" and "dir" keywords without success. Also, I noticed the user manual and I took a look at that but I focused on this segment

    Next, invoke LuaTeX from the terminal:

    luatex --output-directory output-directory document.tex

and since I am using pdflatex with a VSCode extension instead of the actual tool I thought it wasn't suitable for my workflow.
I should have read the documentation more carefully, my bad: I didn't realize *these*
``` latex
\def\markdownOptionHelperScriptFileName{helper-script.lua}
\def\markdownOptionInputTempFileName{temporary-input.md}
\def\markdownOptionOutputTempFileName{temporary-output.tex}
\def\markdownOptionErrorTempFileName{error-output.txt}
\def\markdownOptionOutputDir{output-directory}
\def\markdownOptionCacheDir{output-directory/cache-directory}
\markdownOptionFinalizeCachetrue
\def\markdownOptionFrozenCacheFileName{output-directory/cache-directory/frozen-cache.tex}
```
were actual commands to be entered in a user document, but that those were internal implementations.
As a user I really liked this though :smile: 
`\usepackage[outputDir=build]{markdown}`

Thanks a lot.

**Comment by Witiko** [comment]
Thank you. Let's give a separate example for plain TeX (`\markdownOptionOutputDir`) and LaTeX `outputDir` variants for each of [the I/O options](https://witiko.github.io/markdown/#file-and-directory-names) (`helperScriptFilename`, `inputTempFileName`, `outputTempFileName`, ...).
