### ISSUE TITLE
Enhancement - disable underscore intra-word emphasis

### ISSUE THREAD

**Issue by jendas1** [Witiko/markdown#11]
I tried to write some hybrid markdown-latex text and I quickly encounter problem with math subscripts. I thought about some ways how to deal with that problem, but the easiest solution I found is to disable intra-word emphasis with underscores. This is the "default" in most implementations and specifications, so there is no deviation from standard either.

Because there are more ways how to do it I am proposing it as an enhancement rather than pull request.

This is my naive sketch how it could be implemented.
```lua
parsers.punctuation            = S(",.?!;")
larsers.Emph   = ( parsers.between(parsers.Inline, parsers.asterisk,
                                     parsers.asterisk)
                   + parsers.between(parsers.Inline, (B(parsers.punctuation + parsers.spacing + parsers.asterisk) * parsers.underscore),
                                     (parsers.underscore * #(parsers.punctuation + parsers.spacing + parsers.asterisk + parsers.eof)))
                   ) / writer.emphasis
```
The same situation is with the strong emphasis.

PS: There is a known bug I don't know how to deal with. It's how to match beginning of string (for look behind), so this version fails when asterisk is the first symbol in the string.

**Comment by Witiko** [comment]
> This is the "default" in most implementations and specifications, so there is no deviation from standard either.

I do not think that is the case. Most implementations follow [the original Markdown spec](https://daringfireball.net/projects/markdown/syntax#em), which says that

> But if you surround an * or _ with spaces, it’ll be treated as a literal asterisk or underscore.

What this means is that `_abc def_` and `*uvw xyz*` will be parsed as emphasis (_abc def_ and *uvw xyz*), whereas `_ abc def_` or `*uvw xyz *` will not (_ abc def_ or *uvw xyz *). This synergizes well with the fact that in plain TeX and derivatives, `_` will gobble any following spaces. This means that you can write your mathematics as follows:

```tex
\input markdown
\def\markdownOptionHybrid{true}
\markdownBegin
  $a_ b + c_ d = e$
\markdownEnd
\bye
```

You may also always escape the underscores and asterisks (which will make the character match the `EscapedChar` rule under `Inline`), but the nice property of the previous solution is the fact that it is valid plain TeX, whereas this code will only become valid plain TeX after it has been preprocessed:

```tex
\input markdown
\def\markdownOptionHybrid{true}
\markdownBegin
  $a\_b + c\_d = e$
\markdownEnd
\bye
```
