### ISSUE TITLE
incompatibility caused by `amssymb`

### ISSUE THREAD

**Issue by liziwl** [Witiko/markdown#110]
`taskLists` option introduced at https://github.com/Witiko/markdown/commit/67d39b30b2c62cbbc9fe7d4ed55937436926e249 using the symbol of `amssymb` package.

But `amssymb`  package is incompatible with `unicode-math`. Can implement the `taskLists` option without relying on `amssymb` package?

<https://tex.stackexchange.com/questions/175860/why-does-unicode-math-break-the-kerning-of-accents-in-combination-with-amssymb>

**Comment by liziwl** [comment]
Currently, I must undefine the conflicted macros when I am using `unicode-math`.

```latex
\let\eth\undefined
\let\digamma\undefined
\let\backepsilon\undefined
```

**Comment by Witiko** [comment]
@liziwl In general, you are advised to use [the `plain` LaTeX option](http://witiko.github.io/markdown/#no-default-token-renderer-prototypes) and explicitly define your own token renderers if you need stable behavior. The default token renderers provided by the package are placeholder and subject to incompatible changes without notice.

With that said, we would like to support `unicode-math`, so it would be useful to have the token renderer use it if it is loaded. Can you suggest the corresponding symbols for tasklist boxes in `unicode-math`?

**Comment by zepinglee** [comment]
> Can you suggest the corresponding symbols for tasklist boxes in `unicode-math`?

`unicode-math` provides `\mdlgwhtsquare` instead of `\square`. The following should be ok.

```latex
tickedBox = {$\boxtimes$},
halfTickedBox = {$\boxdot$},
untickedBox = {$\mdlgwhtsquare$},
```

**Comment by Witiko** [comment]
@zepinglee Can you confirm that https://github.com/Witiko/markdown/commit/11392f1f1e942642db27573234c8cdbef2ac5285 fixes your issue?

**Comment by zepinglee** [comment]
> @zepinglee Can you confirm that [9d840be](https://github.com/Witiko/markdown/commit/9d840be4cf97c02837ff79a0b8ef54646ab4e4c1) fixes your issue?

@Witiko Yes, it solves our issues. Thanks for your fix!
