### ISSUE TITLE
Add an option to include arbitrary YAML documents

### ISSUE THREAD

**Issue by Witiko** [Witiko/markdown#117]
Since #22, the Markdown package supports YAML metadata in markdown documents. The metadata may appear anywhere in a markdown document, but they must begin with three dashes (`---`) and end with either three dashes of three dots (`...`), which is vaguely in the spirit of [the YAML spec](https://yaml.org/spec/1.2.2/#22-structures) and [compatible with Pandoc](https://github.com/jgm/pandoc/blob/b7a44f9/src/Text/Pandoc/Readers/Metadata.hs#L135).

Due to the separators, we can't include arbitrary YAML documents using the `\markdownInput` command:
``` tex
\markdownInput[jekyllData]{metadata.yml}  % This won't work
```
There is a good reason for this behavior, too. For example, many documents would be ambiguous without the separators:
```tex
\usepackage[jekyllData]{markdown}
\begin{markdown}
---
- this
- is
- YAML
...
\end{markdown}
\begin{markdown}
- but
- this
- is
- markdown
\end{markdown}
```
However, it would be neat if we could ask the Markdown package to give preference to YAML when things are ambiguous.

I propose to add a boolean option (for example `jekyllDataAlways` or `expectJekyllData`). When enabled, the option would ask Markdown to assume that Markdown documents always begin with a YAML metadata block. In practice, the option would make the surrounding `---` and `...` optional for YAML metadata that appear at the very beginning of a markdown document:
```tex
\usepackage[jekyllData]{markdown}
\markdownInput[expectJekyllData]{metadata.yml}
\begin{markdown*}{expectJekyllData}
- this
- is
- YAML
\end{markdown*}
\begin{markdown}
- but
- this
- is
- markdown
\end{markdown}
```

One alternative would be to overload the current `jekyllData` option and make it mixed rather than boolean (the valid values would be `false` or `"never"`, `true` or `"explicit"`, and `"always"`). However, this would require a smarter type casting code in the Lua CLI (or perhaps drop the booleans?).

Another alternative would be to add a separate command (for example `\yamlInput`) for this. However, I plan to keep the surface area of markdown small and such a command sounds like it belongs to a separate package. Additionally, the above approach is more general and allows users to define `\yamlInput{#1}` as `\markdownInput[jekyllData, expectJekyllData]{#1}`.

**Comment by TeXhackse** [comment]
Concerning the `\yamInput` you  are right. It might be better to have the more general solution in this package because users may configure anything themselves anyway. So I now agree with the option being the better Idea. 

Concerning the option I'd prefer splitting up into more values. Simply because it's the nowerdays more common way to handle it within LaTeX. This would just require  to split up into 2 booleans so `expectJekyllData`and the `jekyllData` boolean internally.

**Comment by Witiko** [comment]
@TeXhackse I just added the `expectJekyllData` Lua option in commit 78dc62b. For more information, please see [the user manual][1].

 [1]: https://witiko.github.io/markdown#option-expectjekylldata
