### ISSUE TITLE
Add facade in front of expl3 inferface for YAML metadata

### ISSUE THREAD

**Issue by Witiko** [Witiko/markdown#118]
Since #22, Markdown supports YAML metadata in markdown documents. Plain TeX supports a [low-level event-based interface][1], which can be appropriate for simple flat metadata, but which is difficult to use for processing complex nested structures:

``` tex
\input markdown
\def\markdownOptionJekyllData{true}
\def\markdownRendererJekyllDataString#1#2{\gdef\name{#2}}
\def\markdownRendererJekyllDataNumber#1#2{\gdef\age{#2}}
\def\markdownRendererJekyllDataEnd{\name{} is \age{} years old.}
\markdownBegin
---
name: Jane Doe
age:  99
---
\markdownEnd
\bye
```

LaTeX provides a [higher-level event-based interface][2], which makes it easier to properly process complex nested structures, but requires the use of the expl3 programming language in a document, which is a markedly different user experience from the rest of the LaTeX interface of the package.

``` tex
\documentclass{article}
\usepackage[jekyllData]{markdown}
\RequirePackage{expl3}
\ExplSyntaxOn
\keys_define:nn
  { markdown/jekyllData }
  {
    name .code:n = { \gdef\name{#1} },
    age  .code:n = { \gdef\age{#1}  },
  }
\ExplSyntaxOff
\markdownSetup{
  renderers = {
    jekyllDataEnd = {\name{} is \age{} years old.},
  }
}
\begin{document}
\begin{markdown}
---
name: Jane Doe
age:  99
---
\end{markdown}
\end{document}
```

To make the high-level expl3 interface more in line with the user experience of Markdown, we may add a `jekyllDataRenderers` key to `\markdownSetup`, which would serve as a facade in front of `\keys_define:nn{markdown/jekyllData} .code:n`:

``` tex
\documentclass{article}
\usepackage[jekyllData]{markdown}
\markdownSetup{
  jekyllDataRenderers = {
    name = {\gdef\name{#1}},
    age = {\gdef\age{#1}},
  },
  renderers = {
    jekyllDataEnd = {\name{} is \age{} years old.},
  },
}
\begin{document}
\begin{markdown}
---
name: Jane Doe
age:  99
---
\end{markdown}
\end{document}
```

At the moment, the high-level expl3 interface is experimental in the sense that it relies on the default renderer prototypes for [the low-level YAML renderers][1], which the users may redefine at any point. Furthermore, the inteface isn't documented in [the user manual][3] and serves as an example of how a programmer could use the low-level interface to build higher-level functionality.

However, if we were to promote the high-level expl3 interface to be an integral part of the LaTeX Markdown interface, we should likely forbid access to the low-level plain TeX interface from LaTeX and document the high-level interface in the user manual as the only official way of accessing the YAML metadata from LaTeX.

 [1]: https://witiko.github.io/markdown/#yaml-metadata-renderers
 [2]: https://mirrors.ctan.org/macros/generic/markdown/markdown.pdf#page=188
 [3]: https://witiko.github.io/markdown/#option-jekylldata

**Comment by Witiko** [comment]
@TeXhackse I will be happy to hear your thoughts on this. It seems to me as the kind of change we may want to make before we advertise our support of YAML in TUGboat.

**Comment by Witiko** [comment]
I gave this some more thought and I am increasingly convinced that the high-level expl3 interface for reacting to YAML metadata is currently defined at the wrong level of abstraction. Specifically, I believe that it should be moved from the LaTeX implementation to the plain TeX interface and properly documented as such.

The Markdown package has historically implemented most core functionality in the plain TeX layer with the LaTeX and ConTeXt layers providing just quality-of-life improvements (aka syntactic sugar) to the user interface. Having the high-level expl3 interface implemented in LaTeX seems nice and tidy on the first glance, since every layer (Lua, plain TeX, LaTeX) does something useful and the code complexity is distributed. However, from the technical standpoint, there is no justification for not having the expl3 implementation in the plain TeX layer, so that ConTeXt and other future formats can benefit from it. There has been a recent shift towards more LaTeX-centric development (see #85 and #107), but I think it's time to course-correct.

Furthermore, default LaTeX renderer prototypes have always been considered placeholders to be redefined by the end user. This also affects the package versioning: changes that would otherwise be considered breaking are good to go if they only concern default LaTeX renderer prototypes. Forbidding access to the jekyllData renderers from LaTeX and building the LaTeX user interface on top of them is a major shift in paradigm. However, if we move the expl3 interface to the plain TeX layer, suddenly the proposed `jekyllDataRenderers` key for the `\markdownSetup` LaTeX command is just a thin abstraction on what is provided by the plain TeX interface and no LaTeX renderer prototype definitions are needed.

**Comment by TeXhackse** [comment]
Concerning the move to the plain TeX layer I totally agree. 

Towords the interface at all I think it's a matter of who your users are. Do they prefer Markdown over LaTeX or are they TeX/LaTeX lovers who just provide the functionality for authors to use markdown. The latter one is my world. So for this it doesn't matter because one would redefine it.

For those who are not as familiar with the structure it probably might be great to simplify the interface for redefinition and use it in the same way as the other renderers would be adjusted.

**Comment by Witiko** [comment]
@TeXhackse Thank you for your thoughts.

Most of Markdown users in my world are authors who would be the happiest if the Markdown package just worked, so that they can cut out the TeX programmer and get to the authoring business. I can sympathize with that, because I am also an author and having to constantly tinker with Markdown can be time-consuming when I am in a rush to get my results published. Therefore, I try to provide sane default renderers, which helps, but it is a far cry from what the TeX-adverse authors would hope for. My students and I are trying to close the gap by producing LaTeX themes for common document classes, but anything custom will always need a TeX programmer such as yourself.

**Comment by Witiko** [comment]
We will introduce expl3 to the TeX layer in #119.

**Comment by Witiko** [comment]
@TeXhackse I moved the expl3 interface from LaTeX implementation to the plain TeX interface in 1ec7931. I also added examples for it to [the user manual][1].

As for defining the key-values directly from the `\markdownSetup` command: Since they keyval package does not allow us to react to unknown keys, we cannot easily remap `\markdownSetup{jekyllDataRenderers = {key = value}}` to `\keys_define:nn { markdown/jekyllData } { key .code:n = {value} }`. Therefore, this issue is blocked by #96.

 [1]: https://witiko.github.io/markdown#latex-example-12

**Comment by Witiko** [comment]
This issue is no longer blocked by #96.
