### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by Witiko** [Witiko/markdown#12]
The logging support is rudimentary:
1. All messages go directly into the standard output of the TeX compiler.
2. Lua errors are not caught and get propagated to the user in different ways depending on the compiler:
   - LuaTeX will properly catch the errors, but
   - with shell bridge, the Lua errors will manifest themselves in the typeset output.
3. The creation of auxiliary files and directories is not properly logged, so external tools like LaTeXMK may not do a proper clean-up.

**Comment by sami10007** [comment]
Hi, 

Can you please state what you have tried? Possibly related: https://stackoverflow.com/a/40336333/54964

How do you log auxiliary files and directories? I think this is the main source of the error. 

Can you please state and/or summarise your shell bridge here?

Best regards, 

Sami

**Comment by Witiko** [comment]
Hello,

> Can you please state what you have tried? Possibly related: https://stackoverflow.com/a/40336333/54964

Sorry, I don't see how the link is related.

> How do you log auxiliary files and directories? I think this is the main source of the error.

I currently do not log them. This is annoying, because then tools such as LaTeXMK that analyze the `.log` files, cannot properly clean up after the compilation. They just don't know about the auxiliary files that the package produced. This is not an error in that it does not prevent the package from functioning but it is definitely something that should be improved in future releases.

> Can you please state and/or summarise your shell bridge here?

What would you like to know? Section 3.2.5 of the package manual (`texdoc markdown`) should provide an accurate description of the architecture.

**Comment by Witiko** [comment]
The first point is now fixed by 49482b842e04991d95a775025a648765677e75d0.

**Comment by Witiko** [comment]
The third point is now fixed by 49482b842e04991d95a775025a648765677e75d0 and c1a39727fe0a7a466b146fd6645b51b23044d994. The `\markdownInput` macro now logs the input Markdown document into `.fls` and `.log` files, which allows external tools such as LaTeXMk to monitor them for changes. External tools such as LaTeXMk only clean up known types of auxiliary files, but at least the package now enables the use of the `-output-directory` TeX engine option, so you have the option to keep all the auxiliary files separate from your sources.

**Comment by Witiko** [comment]
The second point is now fixed by 46dd484.
