### ISSUE TITLE
Latest commits fail to compile TeX4ht example document

### ISSUE THREAD

**Issue by Witiko** [Witiko/markdown#144]
Latest commits fail to compile TeX4ht example document:

https://github.com/Witiko/markdown/actions/runs/2607812642

**Comment by Witiko** [comment]
@michal-h21 This issue appeared sometime between last Monday and this Monday. Do you think it might be related to the new definition of `\MakeUppercase` and `\MakeLowercase` in LaTeX 2022-06-01-PL4, which landed in TeX Live on 2022-07-03?

**Comment by michal-h21** [comment]
@Witiko yes, there was an issue with `\MakeUppercase`. It was patched by TeX4ht to fix some issues with accents. But this code was ancient, and probably not useful at all any more, even if it didn't break with the latest LaTeX kernel update. So I removed it from TeX4ht sources, but it seems that the fixed version of `latex.4ht` is still not available in TeX Live. I hope it will be there soon.

**Comment by Witiko** [comment]
@michal-h21 It seems that the patch to TeX4ht has bubbled up into the texlive/texlive docker images and the example document compiles fine again. I reverted commit https://github.com/Witiko/markdown/commit/9fbb5c60462deb8705d079b9b8eff45ba52cdc3c and I am closing this issue.
