### ISSUE TITLE
How highlighting a code source ?

### ISSUE THREAD

**Issue by thibaultfalque** [Witiko/markdown#16]
Hi, 
Thanks for this package. 
I don't understand how highlighting a code source in the generated PDF. 

Exemple in my markdown I have a code block with xml "label" and in my pdf I have: 
![Result PDF](https://cloud.githubusercontent.com/assets/6603358/25666930/3c3b2adc-3022-11e7-826a-7a304296677f.png)

The xml code isn't highlighting and the format is not correct. 

Thanks for your help. 

TF.

**Comment by Witiko** [comment]
Fenced blocks are a syntax extension; you need to enable it via `\markdownSetup{fencedCode}` or `\usepackage[fencedCode]{markdown}` (or `\def\markdownOptionFencedCode{true}` if you are not using LaTeX). Without the syntax extension enabled, your code is likely parsed just as an inline code span.

**Comment by thibaultfalque** [comment]
Hi, 
Thanks for your answer it's work? Is it possible to color the render in PDF ?

**Comment by Witiko** [comment]
If you have the `minted` or the `listings` package loaded, then either of these will be used to highlight your code. Otherwise, you can redefine the `\markdownRendererInputFencedCode` macro to perform the rendering the way you want like this:
```tex
\def\markdownRendererInputFencedCode#1#2{%
  \inputminted{#2}{#1}%
}
```

**Comment by thibaultfalque** [comment]
Thanks very much !
