### ISSUE TITLE
Improve ConTeXt interface

### ISSUE THREAD

**Issue by Witiko** [Witiko/markdown#17]
[The ConTeXt interface](http://mirrors.ctan.org/macros/generic/markdown/markdown.html#context) would benefit from a proper user interface such as [the one LaTeX has](http://mirrors.ctan.org/macros/generic/markdown/markdown.html#latex). Being an academician first and a TeX enthusiast second, I have only had cursory exposure to ConTeXt. Therefore, I don't feel I understand the ConTeXt philosophy and syntax conventions enough to design a user interface for it. This leaves the ConTeXt users of the Markdown package with [the plain TeX interface](http://mirrors.ctan.org/macros/generic/markdown/markdown.html#plain-tex), which is not ugly per se, but which does feel out of place in a ConTeXt document.

See also [the accurate description of the status quo](https://mailman.ntg.nl/pipermail/ntg-context/2017/088651.html) by on the ConTeXt mailing list by @mojca:

> Hi,
> 
> There's a really nice module for processing markdown:
>      https://github.com/Witiko/markdown
> that has been presented during the TUG meeting and is included in TeX Live.
> 
> It theoretically works for ConTeXt (the output is perfectly usable),
> but it needs a cleanup of the user interface to turn the options on
> and off.
> 
> For example, it would be nice to use something like
> 
>     \setupmarkdown
>         [fencedCode=true]
> 
> rather than
> 
>     \def\markdownOptionFencedCode{true}
> 
> Is anyone willing to look into the code and help the author fix the interface?
> 
> (I can add it to our distribution if needed.)
> 
> Mojca

I will appreciate any suggestions on how the user interface for ConTeXt should be redesigned to better fit in with the rest of ConTeXt and which ConTeXt mechanisms should be used to implement the suggested redesign.

**Comment by sami10007** [comment]
Hi, 

Do you have any crafts on this? Any tests? Any timeline? Any first goals? 

Do you they mean by the following the same as `\setupmarkdown[fencedCode=true]`?
```
 \setupmarkdown
        [fencedCode=true]
```

Best regards, 

Sami

**Comment by Witiko** [comment]
Hi,

> Do you have any drafts on this? Any tests? Any timeline? Any first goals?

There is currently no timeline, I am only just getting my feet wet with ConTeXt. The general idea is to have an interface similar to the one for LaTeX, so that ConTeXt users do not have to use the plain TeX interface to configure the package. However, this interface also needs to be consistent with the logic and the syntax of ConTeXt; therefore I feel I need to become more familiar with ConTeXt before drafting the interface. Alternatively, I would be willing to add an interface prepared by a ConTeXt user -- patches, pull requests, and proposals are welcome.

> Do you they mean by the following the same as `\setupmarkdown[fencedCode=true]`?
> 
>      \setupmarkdown
>             [fencedCode=true]

Sure, there are equivalent from the viewpoint of TeX.

**Comment by Witiko** [comment]
@mojca, I recall that [you proposed a more complete ConTeXt syntax extension](https://mailman.ntg.nl/pipermail/ntg-context/2017/088651.html) to the Markdown package back in 2018 after the TUG@BachoTeX 2017 conference. Have you noticed any desire to integrate the package more tightly with ConTeXt or other recent feedback relevant to us from the ConTeXt users?

**Comment by adityam** [comment]
@Witiko I have never looked at the package in detail, but I can help with the ConTeXt interface. Can you give more details on what you are looking at.

From the discussion in this thread, I understand that the current interface is driven using macros. Changing that to keyword interface should be straight forward. Is there a document where all the interface options are described?

In general, if you have any questions on anything related to ConTeXt, feel free to ping me.

**Comment by Witiko** [comment]
> @Witiko I have never looked at the package in detail, but I can help with the ConTeXt interface. Can you give more details on what you are looking at.
> From the discussion in this thread, I understand that the current interface is driven using macros. Changing that to keyword interface should be straight forward. Is there a document where all the interface options are described?

@adityam Thank you for your response. In LaTeX, users can [configure the package when loading the package](http://mirrors.ctan.org/macros/generic/markdown/markdown.html#latex):

```latex
\documentclass{article}
\usepackage[hybrid, pipeTables]{markdown}
...
\begin{document}
...
```

They can also [configure the package using the `\markdownSetup` command](http://mirrors.ctan.org/macros/generic/markdown/markdown.html#table-renderer):

```latex
...
\markdownSetup{
  hybrid,
  tables,
  renderers = {
    table = { ... },
  },
}
...
```

They can also [configure the package locally for every piece of markdown code](http://mirrors.ctan.org/macros/generic/markdown/markdown.html#latex):

```latex
...
\begin{markdown}
$\sqrt{-1}$ *equals* $i$
\end{markdown}

\begin{markdown*}{hybrid}
$\sqrt{-1}$ *equals* $i$
\end{markdown*}
...
```

For ConTeXt, [there is no such support and the users have to rely on redefining macros, which seems out-of-place in a ConTeXt document](http://mirrors.ctan.org/macros/generic/markdown/markdown.html#context):

```tex
\usemodule[t][markdown]
\starttext

\startmarkdown
$\sqrt{-1}$ *equals* $i$.
\stopmarkdown

\def\markdownOptionHybrid{true}
\startmarkdown
$\sqrt{-1}$ *equals* $i$.
\stopmarkdown

\stoptext
```

I am looking for a suggestion as to how things should look, so that the interface is more friendly to the ConTeXt users.

> In general, if you have any questions on anything related to ConTeXt, feel free to ping me.

Thanks again, much appreciated.

**Comment by mojca** [comment]
For ConTeXt one would probably want to use something like this
```tex
\usemodule
    [markdown]
\setupmarkdown
    [hybrid=off,
     tables=on]

\starttext

\startmarkdown
$\sqrt{-1}$ *equals* $i$.
\stopmarkdown

\startmarkdown[hybrid] % or hybrid=on
$\sqrt{-1}$ *equals* $i$.
\stopmarkdown

\stoptext
```

But there are some other options that could use other tricks. I've seen the `blankBeforeHeading`  or `shiftHeadings` option, for example, which could be handled different, by merely setting up the headings in the desired way in ConTeXt. I wouldn't want markdown module to be too smart for me. Just convert the markdown heading into the suitable tex heading, and I can set up how the headings themselves look like in my own way.

@adityam: There is a long document with [documentation](http://mirrors.ctan.org/macros/generic/markdown/markdown.html) describing all options in detail.

It's unlikely that I would manage to sit down and spend any reasonal amount of time for this myself, in particular given that I'm unlikely to ever use MarkDown myself (I hardly do any typesetting at all these days to be honest). I could review / provide feedback. But @adityam and some others like Wolfgang Schuster are big experts and can help with some excellent examples of good coding practice for ConTeXt.

**Comment by Witiko** [comment]
> For ConTeXt one would probably want to use something like this
>
> [...]
>
> It's unlikely that I would manage to sit down and spend any reasonal amount of time for this myself, in particular given that I'm unlikely to ever use MarkDown myself (I hardly do any typesetting at all these days to be honest). I could review / provide feedback. But @adityam and some others like Wolfgang Schuster are big experts and can help with some excellent examples of good coding practice for ConTeXt.

Thank you, this is much appreciated.

> But there are some other options that could use other tricks. I've seen the `blankBeforeHeading` or `shiftHeadings` option, for example, which could be handled different, by merely setting up the headings in the desired way in ConTeXt. I wouldn't want markdown module to be too smart for me. Just convert the markdown heading into the suitable tex heading, and I can set up how the headings themselves look like in my own way.

The `blankBeforeHeading` option is a parser option, which decides whether

```markdown
text
# heading
other text
```

will be parsed as follows:

> text # heading other text

or as follows:

> text
>
> # heading
> other text

The Markdown spec is ambiguous in this regard, so we provide an option to choose the parser flavor. In general, most options control the parser, not the way Markdown elements are rendered. For this, there are renderers (redefinable TeX commands to which the Markdown elements expand to) and, indeed, the standard formatting functions of the ConTeXt format.

**Comment by Witiko** [comment]
> For ConTeXt one would probably want to use something like this
>
> [...]
>
> It's unlikely that I would manage to sit down and spend any reasonal amount of time for this myself, in particular given that I'm unlikely to ever use MarkDown myself (I hardly do any typesetting at all these days to be honest). I could review / provide feedback. But @adityam and some others like Wolfgang Schuster are big experts and can help with some excellent examples of good coding practice for ConTeXt.

@mojca Thank you, this is much appreciated.

> But there are some other options that could use other tricks. I've seen the `blankBeforeHeading` or `shiftHeadings` option, for example, which could be handled different, by merely setting up the headings in the desired way in ConTeXt. I wouldn't want markdown module to be too smart for me. Just convert the markdown heading into the suitable tex heading, and I can set up how the headings themselves look like in my own way.

The `blankBeforeHeading` option is a parser option, which decides whether

```markdown
text
# heading
other text
```

will be parsed as follows:

> text # heading other text

or as follows:

> text
>
> # heading
> other text

The Markdown spec is ambiguous in this regard, so we provide an option to choose the parser flavor. In general, most options control the parser, not the way Markdown elements are rendered. For this, there are renderers (redefinable TeX commands to which the Markdown elements expand to) and, indeed, the standard formatting functions of the ConTeXt format.

**Comment by adityam** [comment]
> @adityam: There is a long document with [documentation](http://mirrors.ctan.org/macros/generic/markdown/markdown.html) describing all options in detail.

Thanks. I will go over this and try to understand all the options and then
come back with suggestions of an interface that will fit with ConTeXt style.

**Comment by mojca** [comment]
> The `blankBeforeHeading` option is a parser option,
> /.../
> The Markdown spec is ambiguous in this regard

Oh, I'm sorry. Yes, then this option makes perfect sense. I thought it was about how output was supposed to look like.

**Comment by adityam** [comment]
I am still trying to understand the overall structure and hope you don't mind me asking clarifying questions here. I am assuming that in ConTeXt, anyone running the module will be using MkIV (luatex engine). 

1. By default, this module creates too many files.Even a simple hello world file creates `jobname.markdown.in` and `cacheDir/md5sum.md.tex`. Why? Why not simply store them in memory and write these file to disk if needed. That is the route taken my `m-markdown`. As a ConTeXt user I have gotten user to **no** temp file except a `.log` file and a `tuc` file. Any other temp file should be written only if absolutely necessary. 

2. Is there a Lua function, which will take a string and an options table and return a parsed string? That will be the simplest route to go for ConTeXt instead of reading and writing to temp files.

2. I am by no means a Lua expert, but looking at the coding style used in ConTeXt I have always assumed that calls of the form `namespace.function` is more expensive than `local function = namespace.function`. `markdown.lua` uses explicit namespaces for the the parser code `parser.something..`. Out of curiosity, is there any speed penalty due to using this style?

3. I am thinking that a good way to use the functionality will be write a context interface `t-markdown.mkiv` from scratch that does not call the plain tex interface at all. To streamline the transition, I will start writing a `t-new-markdown.mkiv`, which can then perhaps be merged if everything goes well. Is this okay?

4. Do you have a test suite with various examples? That will make it easier for me rather than creating examples "by hand".

**Comment by Witiko** [comment]
> 1. By default, this module creates too many files.

The main markdown document could be stored in-memory when LuaTeX is used. However, the [code blocks][] markdown renderers expect a filename of the code block as an argument, so these would be difficult to get rid of without breaking the interface.

Note, however, that having auxiliary files can be useful. As an example, the Czech typography forbids ending a line with non-syllabic prepositions. To address this issue, the [vlna][] program can be used to add a non-breaking space after all non-syllabic prepositions in a text file. With auxiliary files, you can easily use the `vlna cacheDir/*.md.tex` command to fix all Markdown texts in your document.

 [code blocks]: http://mirrors.ctan.org/macros/generic/markdown/markdown.html#code-block-renderers
 [vlna]: https://manpages.debian.org/testing/texlive-binaries/vlna.1.en.html

> 2. Is there a Lua function, which will take a string and an options table and return a parsed string?

Yes, there is [the Lua interface][lua interface].

 [lua interface]: http://mirrors.ctan.org/macros/generic/markdown/markdown.html#lua-module

> 3. [...] Out of curiosity, is there any speed penalty due to using this style?

There is [a minor speed penalty], since a hash table is used instead of local variables. [This change was necessary][] for us, because there is an upper limit on the number of local variables in Lua, which we hit.

 [a minor speed penalty]: https://github.com/jgm/lunamark/pull/25
 [this change was necessary]: https://github.com/jgm/lunamark/issues/24

> 4. [...] Is this okay?

You will likely want to reuse some parts of `t-markdown.tex`, such as the ConTeXt renderers. Otherwise, yes, that would be perfect.

> 5. Do you have a test suite with various examples?

We have a rich set of [unit tests][].

 [unit tests]: https://github.com/Witiko/markdown/tree/master/tests

**Comment by adityam** [comment]
> > 1. By default, this module creates too many files.
> 
> The main markdown document could be stored in-memory when LuaTeX is used. However, the [code blocks](http://mirrors.ctan.org/macros/generic/markdown/markdown.html#code-block-renderers) markdown renderer expects a filename with the code block as an argument; these auxiliary files would be difficult to get rid of without breaking the established interface.

OK. I'll stick with this for now.

> > 1. Is there a Lua function, which will take a string and an options table and return a parsed string?
> 
> Yes, there is [the Lua interface](http://mirrors.ctan.org/macros/generic/markdown/markdown.html#lua-module).

I meant something that does not create temp files. But I'll not go down that path for now.

> > 1. [...] Is this okay?
> 
> You will likely want to reuse some parts of `t-markdown.tex`, such as the ConTeXt renderers. Otherwise, yes, that would be ideal, thank you.

Perhap. For most of the features, I think that it is better to follow the ConTeXt style for defining (and therefore changing) rendering options. For example, let's consider a simple ConTeXt file:

```
\usemodule[new-markdown]

\starttext
\startmarkdown
  Test of *basic* `markdown` **features**
\stopmarkdown
\stoptext
```

Here is a basic implmentation of the `t-new-markdown.mkiv` module which is able to parse and typeset the above example:

```
\unprotect

\definehighlight
  [markdownRendererEmphasis]
  [style=\em]

\definehighlight
  [markdownRendererStrongEmphasis]
  [style=bold]

\definehighlight
  [markdownRendererCodeSpan]
  [style=mono]

\startluacode
  thirddata = thirddata or {}
  thirddata.markdown = require("markdown")

  local markdown = thirddata.markdown

  function markdown.typesetbuffer(options, name)
      local convert = markdown.new(options)
      context(convert(buffers.getcontent(name)))
  end
\stopluacode

% Basic interface, without any option parsing
\definebuffer[markdown]

\unexpanded\def\stopmarkdown
      {\ctxlua{thirddata.markdown.typesetbuffer(nil, "\thedefinedbuffer{markdown}")}}

\protect
```

Using high-level ConTeXt macros (\definehighlight etc) instead of low level TeX commands (\def\...) etc has the advantage that (i) you get a simple key-level driven interface to change features, (e.g., to get red colored emphasis, simply add `\setuphighlight[markdownRendererEmphasis][color=red]`. (ii) Generating structured outputs such as tagged-pdf and XHTML or EPUB export work out of the box.

**Comment by Witiko** [comment]
> I meant something that does not create temp files

Not really. The auxiliary files are an early design decision, which affects the whole code base.

> Perhap. For most of the features, I think that it is better to follow the ConTeXt style for defining (and therefore changing) rendering options.

That is fine, but the content of the renderer definitions can be kept.

**Comment by Witiko** [comment]
@adityam Any progress with the interface? In your https://github.com/Witiko/markdown/issues/17#issuecomment-625475970, there is a redefinition of `\startmarkdown` and `\stopmarkdown`, which the package [already defines](http://ftp.cvut.cz/tex-archive/macros/generic/markdown/markdown.pdf#page=161), and a more idiomatic example code for redefining [Markdown renderers](http://mirrors.ctan.org/macros/generic/markdown/markdown.html#markdown-tokens), which is appreciated and will make its way to user examples for Markdown 2.10.0. However, the biggest desiderata are [the Markdown options](http://mirrors.ctan.org/macros/generic/markdown/markdown.html). Here is the current ConTeXt interface for options:

```tex
\usemodule[t][markdown]
\def\markdownOptionPipeTables{true}
\def\markdownOptionTableCaptions{true}
\starttext

\startmarkdown
$\sqrt{-1}$ *equals* $i$.
\stopmarkdown

\def\markdownOptionHybrid{true}
\startmarkdown
$\sqrt{-1}$ *equals* $i$.
\stopmarkdown

\stoptext
```

Compare with the LaTeX interface for options, which is much more compact and idiomatic:

```tex
\documentclass{article}
\usepackage[pipeTables, tableCaptions]{markdown}
\begin{document}

\begin{markdown}
$\sqrt{-1}$ *equals* $i$
\end{markdown}

\begin{markdown*}{hybrid}
$\sqrt{-1}$ *equals* $i$
\end{markdown*}

\end{document}
```

**Comment by Witiko** [comment]
> Using high-level ConTeXt macros (\definehighlight etc) instead of low level TeX commands (\def...) etc has the advantage that (i) you get a simple key-level driven interface to change features, (e.g., to get red colored emphasis, simply add `\setuphighlight[markdownRendererEmphasis][color=red]`. (ii) Generating structured outputs such as tagged-pdf and XHTML or EPUB export work out of the box.

@adityam I would add these to the example documents, but we support ConTeXt MkII and the `\definehighlight` command doesn't seem to be available in MkII.

**Comment by adityam** [comment]
On Sun, 8 Aug 2021, Vít Novotný wrote:

> > Using high-level ConTeXt macros (\definehighlight etc) instead of low level TeX commands (\def...) etc has the advantage that (i) you get a simple key-level driven interface to change features, (e.g., to get red colored emphasis, simply add `\setuphighlight[markdownRendererEmphasis][color=red]`. (ii) Generating structured outputs such as tagged-pdf and XHTML or EPUB export work out of the box.
> 
> @adityam I would add these to the example documents, but we support ConTeXt MkII and the `\definehighlight` command doesn't seem to be available in MkII.

Would it be possible to provide separate examples for MkII and MkIV. MkII has been in maintenance-only mode for almost a decade now. So, any ConTeXt user still using MkII will be an old user who is using MkII on a long-term project. Almost all ConTeXt documentation assumes that a new user is starting with either MkIV or even LMTX.

**Comment by Witiko** [comment]
@adityam We can definitely fork [examples/context.tex][1] into two separate files: `context-mkii.tex` for MkII and `context-mkiv.tex` for MkIV. Then, we can simplify the `Makefile` as follows:

``` diff
diff --git a/examples/Makefile b/examples/Makefile
index e084a9a..548e4e2 100644
--- a/examples/Makefile
+++ b/examples/Makefile
@@ -14,13 +14,11 @@ all: $(OUTPUT)
 	$(MAKE) clean
 
 # This target typesets the ConTeXt example using the Mark II format.
-context-mkii.pdf: context.tex example.tex
-	cp context.tex context-mkii.tex
+context-mkii.pdf: context-mkii.tex example.tex
 	texexec --passon="--shell-escape --8bit" context-mkii.tex
 
 # This target typesets the ConTeXt example using the Mark IV format.
-context-mkiv.pdf: context.tex example.tex
-	cp context.tex context-mkiv.tex
+context-mkiv.pdf: context-mkiv.tex example.tex
 	context context-mkiv.tex
 
 # This target typesets the LaTeX example using the pdfTeX engine.
```

 [1]: https://github.com/Witiko/markdown/blob/main/examples/context.tex

**Comment by Witiko** [comment]
I added [an example document for ConTeXt MkIV][1].
Many thanks for your help, @adityam!

 [1]: https://github.com/Witiko/markdown/blob/main/examples/context-mkiv.tex

**Comment by Witiko** [comment]
It would be neat if we could have a `\markdownSetup` command that would replace this:
``` tex
% Set options of the Markdown module.
\def\markdownOptionHashEnumerators{true}
\def\markdownOptionDefinitionLists{true}
\def\markdownOptionSmartEllipses{true}
\def\markdownOptionFootnotes{true}
\def\markdownOptionInlineFootnotes{true}
\def\markdownOptionFencedCode{true}
\def\markdownOptionContentBlocks{true}
\def\markdownOptionPipeTables{true}
\def\markdownOptionTableCaptions{true}
\def\markdownOptionTaskLists{true}
```

with this:

``` tex
% Set options of the Markdown module.
\markdownSetup[hashEnumerators,
               definitionLists,
               smartEllipses,
               footnotes,
               inlineFootnotes,
               fencedCode,
               contentBlocks,
               pipeTables,
               tableCaptions,
               taskLists]
```

I wonder how we could do that.

**Comment by adityam** [comment]
I would recommend a slightly more context-ish syntax: `\setupmarkdown[...]` instead of `\markdownSetup` and using `key=value` rather than `option` (with only `option`, you need to figure out how to disable things). 

ConTeXt doesn't use CamelCase a lot ... nevertheless, if you can consider `HashEnumerators=yes` (note capital H), then the interface is rather straight forward:
    \unprotect

    \definenamespace
      [markdown]
      [   \c!type=module,
          \c!name=markdown,
            setup=\v!list,
        \s!parent=markdown,
      ]

    \define[1]\markdown_parse_option%
        {\doifelse{\markdownparameter{#1}}\v!yes
            {\setvalue{markdown#1}{true}}
            {\setvalue{markdown#1}{false}}}

    \define\initialize_markdown
      {\processcommalist
            [
              HashEnumerators,
              DefinitionLists,
              SmartEllipses,
              Footnotes,
              InlineFootnotes,
              FencedCode,
              ContentBlocks,
              PipeTables,
              TableCaptions,
              TaskLists,
            ]\markdown_parse_option}

    \appendtoks \initialize_markdown \to \everysetupmarkdown
            
    \protect

You'd need to initialize the values somewhere:

    \setupmarkdown
      [
        HashEnumerators=yes,
        DefinitionLists=yes,
        SmartEllipses=yes,
        Footnotes=yes,
        InlineFootnotes=yes,
        FencedCode=yes,
        ContentBlocks=yes,
        PipeTables=yes,
        TableCaptions=yes,
        TaskLists=yes,
      ]

Example usage:

    \show\markdownHashEnumerators

    \setupmarkdown[HashEnumerators=no]

    \show\markdownHashEnumerators

If you'd prefer `hashEnumerators=yes` (with lowercase h), it may still be possible with some `\uppercase` magic, but my TeX-fu is weak when it comes to expansion and stuff...

**Comment by adityam** [comment]
... and of course, lowercase `hashEumerator=yes` is easy if we just type out everything:

    \define\initialize_markdown
        {%
           \doifelse{\markdownparameter{hashEnumerators}}\v!yes
              {\def\markdownHashEnumerators{true}}
              {\def\markdownHashEnumerators{false}}
         % Same for other options
        }

**Comment by Witiko** [comment]
@adityam Thank you, that is helpful.

> ConTeXt doesn't use CamelCase a lot ...

Does it use snake_case then? We could still make that work automatically.

> ... nevertheless, if you can consider HashEnumerators=yes (note capital H), then the interface is rather straight forward

The catch is that not all options are boolean. For example, [the `slice` option][1] is a string,

 [1]: https://witiko.github.io/markdown/#slice

> ... and of course, lowercase `hashEumerator=yes` is easy if we just type out everything:

That's what the LaTeX interface currently does. However, it's a pain to maintain, so perhaps we should add runtime information about types, so that this aspect of the package can be automated.

**Comment by adityam** [comment]
ConTeXt doesn't use snake_case either. Almost all options are single word. 

Another option is not to do _any_ parsing at the TeX end. Simply pass everything _as input by the user_ to Lua: something like ...

```
\directlua{ markdownSetup( { hashEnumerator = "\markdownparameter{HashEnumerator}", .... } )
```
This is laborious, but has to be done once in each format. Then, at the lua end, you can read the value of `options.hashEnumerator` and based on the value `yes` or `no` set the appropriate lua variable to be true or false. Since the parsing code is in Lua, we are not restricted by the limitations of TeX macros, and can easily write code which automates the processing.

**Comment by Witiko** [comment]
This issue is blocked by https://github.com/Witiko/markdown/issues/124.
