### ISSUE TITLE
Error in Markdown bulleted lists: "Too deeply nested. \markdownRendererUlBeginTight"

### ISSUE THREAD

**Issue by telamonian** [Witiko/markdown#2]
First I want to say that I love the Markdown package. Thanks for putting this up here.

I'm a big fan of using bulleted lists in Markdown to write outlines. I'm trying to add an outline to a paper that I'm working on in Latex, but I keep getting the same error whenever I try to render it. Here's a complete example of what Texstudio will complain about:

    003fc04eb7c4a930393129e07112a107.md.tex error line 19: Too deeply nested. \markdownRendererUlBeginTight

I dug around a little, and apparently there's a hard limit for list nesting depth built into TeX at some deep level. According to various sources (such as [http://tex.stackexchange.com/questions/41408/a-five-level-deep-list](http://tex.stackexchange.com/questions/41408/a-five-level-deep-list)) the way to work around it is to use the `enumitem` package. I tried adding some `enumitem` stuff to the preamble of my document:

    \usepackage{enumitem}
    \setlistdepth{20}
    \renewlist{itemize}{itemize}{20}

    % use dots for all levels
    \setlist[itemize]{label=$\cdot$}

only now Texstudio is reporting a different set of errors:

    003fc04eb7c4a930393129e07112a107.md.tex error line 2: Package enumitem Error: Undefined label. \markdownRendererUlItem 7
    003fc04eb7c4a930393129e07112a107.md.tex error line 3: Package enumitem Error: Undefined label. \markdownRendererUlItem r
    003fc04eb7c4a930393129e07112a107.md.tex error line 4: Package enumitem Error: Undefined label. \markdownRendererUlItem b
    ...

I think the `enumitem` solution is correct, but I'm such a Latex novice that I'm getting the syntax /placement wrong somewhere. Any suggestions on how to fix my fix for list depth?

If you give me a couple of pointers, I'd also be glad to get a pull request together so that deeper lists can be turned on as an option in the Markdown packaged itself, if you'd like.

**Comment by telamonian** [comment]
Just as I finished writing up the issue, I found the magic words to add to my preamble:

    \usepackage{enumitem}
    \setlistdepth{20}
    \renewlist{compactitem}{itemize}{20}
    \setlist[compactitem]{label=$\cdot$}

Now I can control the maximum depth however I like.

It would be cool to add this to the Markdown package itself, so I'll leave the issue open if you want to coordinate on that. Otherwise, it's fixed for me, so feel free to close this.

**Comment by Witiko** [comment]
Thank you for the kind words. I am glad that the package is useful to you and that you found a solution to your problem. The `markdown` package loads the `paralist` package to render compact lists, so it is likely that the `paralist` and `enumitem` packages clashed. Hopefully your solution will be of use to other users.

At this time, I am not planning to add the solution to the package. I am keeping the list of dependencies down (to prevent further clashes) and the main purpose of the package is to translate markdown markup to TeX macros (such as `\markdownRendererUlBeginTight`). The package provides sane definitions for these macros, but it is up to the user to redefine the macros and load the packages they need.
