### ISSUE TITLE
”DOSKEY” issue with \markdownInput

### ISSUE THREAD

**Issue by nopria** [Witiko/markdown#217]
Compiling a simple source like

```
% to be compiled with XeLaTex
\documentclass{book}

\usepackage{fontspec}

\usepackage{polyglossia}
\setdefaultlanguage{italian}

\usepackage{markdown}

\begin{document}
\markdownInput{test.md}
\end{document}
```

where `test.md` is just

```
# Ciao

Ciao.
```

I get the following error in log

```
Package luabridge Info: Executing a helper Lua script from file
(luabridge)             \markdownOptionHelperScriptFileName 

 ()
Missing character: There is no ^^8a in font [lmroman10-regular]:mapping=tex-tex
t;!
(_markdown_test01/f0730b7895e05c829adfeff085ee010c.md.tex [1

] [2

]
```

and in the resulting PDF an unwanted line is printed just before the imported markdown:

```
”DOSKEY” non � riconosciuto come comando interno o esterno, un pro-
gramma eseguibile o un file batch.
```

("DOSKEY" is not recognized as an internal or external command, executable program or batch file.)

I use MiKTeX under Windows 10 and compile with XeLaTeX with `--shell-escape` option. About one year ago I compiled in the same way many XeLaTeX documents using markdown package and such an issue was not present.

Any clue?

**Comment by Witiko** [comment]
@nopria I am sorry, I cannot reproduce your issue on a clean TeX Live install:

- https://www.overleaf.com/8552948758kytkchtmbvmp

**Comment by nopria** [comment]
In case somebody wants to reproduce the issue with MikTeX, I attach the actual TexWorks compiler configuration for XeLaTeX, which is the default one plus the `--shell-escape` option.

![Clipboard01_opt](https://user-images.githubusercontent.com/4848618/201710984-c3d91a52-5429-4ad3-9350-3e65d2c882c1.png)

**Comment by Witiko** [comment]
Possibly related to [the lt3luabridge library][1] that we use to interface with Lua from non-LuaTeX engines.

 [1]: https://github.com/witiko/lt3luabridge

**Comment by Witiko** [comment]
Closing the issue due to inactivity.
