### ISSUE TITLE
Allow Jekyll Frontmatter

### ISSUE THREAD

**Issue by krono** [Witiko/markdown#22]
[Jekyll Frontmatter](https://jekyllrb.com/docs/frontmatter/) (A YAML block before actual markdown text) is commonly used with github pages and markdown.

It would be great to be able to

 * have Frontmatter in included Markdown files and maybe
 * set a callback/command to process the contents.

-----

Background: I have some people giving me tex files that includes things like authors, title, etc. I really would like to have that as markdown, but cannot deal with the metadata.

E.g., currently I get
```LaTeX
\author{John Doe}
\title{The Theory of Everything}
\maketitle
\begin{abstract}
foo
\end{abstract}

Lorem \emph{ipsum} ...
```

But I would like
```Markdown
---
author: John Doe
title: The Theory of Everything
abstract: >
  foo
---

Lorem *ipsum* ...
```
And then turn the latter into the forme

**Comment by Witiko** [comment]
Hello,

the package currently does not support YAML blocks. However, since all syntax is mapped to TeX macros, you can abuse the existing syntax to achieve the desired effect:

```tex
\documentclass{article}
\usepackage{markdown}
\def\markdownRendererHeadingOne#1{\author{#1}}
\def\markdownRendererHeadingTwo#1{\title{#1}}
\def\markdownRendererBlockQuoteBegin{\maketitle\begin{abstract}}
\def\markdownRendererBlockQuoteEnd{\end{abstract}}
\def\markdownRendererHorizontalRule{%
  % The end of the front matter.
  \def\markdownRendererHeadingOne##1{\markdownRendererHeadingOnePrototype{##1}}%
  \def\markdownRendererHeadingTwo##1{\markdownRendererHeadingTwoPrototype{##1}}%
  \def\markdownRendererBlockQuoteBegin{\markdownRendererBlockQuoteBeginPrototype}%
  \def\markdownRendererBlockQuoteEnd{\markdownRendererBlockQuoteEndPrototype}%
  \def\markdownRendererHorizontalRule{\markdownRendererHorizontalRulePrototype}}
\begin{document}
\begin{markdown}
# John Doe
## The Theory of Everything
> foo

***

# Level 1 heading
## Level 2 heading
Lorem *ipsum* ...
\end{markdown}
\end{document}
```
![latex](https://user-images.githubusercontent.com/603082/35759353-63dc7d5e-0879-11e8-9598-f3c15df8f674.png)

**Comment by Witiko** [comment]
Of course, YAML blocks are nicer if you use your Markdown documents for multi-target publishing. Sadly, the package currently does not support them. If you have a partial working implementation, I would be happy to help you finalize and merge it.

You might also want to consider using external tools that support YAML blocks and produce LaTeX markup, such as Pandoc or MultiMarkdown. The downside is that you do not get such a nice interface to control the form of the resulting document.

**Comment by TomBener** [comment]
Thanks for creating the amazing package!

I wonder whether the package could convert the yaml block to the proper PDF metadata generated by hyperref at the moment? for example, yaml block in markdown file is like:

```
title: bah1
author: bah2
subject: bah3
......

```
want to converted to LaTeX👇:
```
pdftitle={bah1},
pdfauthor = {bah2},
pdfsubject = {bah3},
......
```

Alternatively, I just want to ignore the yaml when compiling the LaTeX file. Now, the `markdown` package regards the yaml block as the normal body. As the yaml block is essential for some purposes, I don't want to delete it but just want the package to neglect it? Is it possible to make it? Thanks!

**Comment by TeXhackse** [comment]
Oh the TeX way can easily be added, give me a second.

**Comment by krono** [comment]
Also I would propose
`\markdownRendererSetFrontmatterData`
instead of
`\markdownRendererSetJekyllData`

**Comment by Witiko** [comment]
Or perhaps more declarative `\markdownRendererFrontmatterItem`. We could even add the surrounding `\markdownRendererFrontmatterBegin` and `markdownRendererFrontmatterEnd`, so that the front matter gets the same handling as definition lists, numbered lists and bullet lists:

``` tex
\markdownRendererFrontmatterBegin
\markdownRendererFrontmatterItem{author}{John Doe}
\markdownRendererFrontmatterItem{title}{The Theory of Everything}
\markdownRendererFrontmatterItem{abstract}{foo}
\markdownRendererFrontmatterEnd
```

**Comment by Witiko** [comment]
I have added this feature to the 2.10.0 milestone. If you'd like to clean this up into a PR, that would be appreciated; otherwise, I can take over from here. I will also be writing a TUGboat article about the new features; we could share authorship if you'd like.

**Comment by TeXhackse** [comment]
I will try to do so, but won't manage to have another look at it before the weekend.

**Comment by Witiko** [comment]
That's no issue at all. We will also want to document the additions, but I can take that off your hands.

**Comment by TeXhackse** [comment]
I cleaned if up a bit and tried to follow the documentation structure. I implemented the two-argument variant, because as we realized this might be easier for average users. One could easily use it to fill a keyval structure anyway. 

It's still not clean so I just opened a draft PR and will continue as much as possible, but due to a lack of time that might be not that helpful at all.

**Comment by Witiko** [comment]
@TeXhackse Thank you. I will take a look and help finish the PR.

**Comment by Witiko** [comment]
Since we are close to the release of Markdown 2.10.0 and #77 is far from completed, I am thinking of postponing this issue to the next minor version. What do you think?

**Comment by TeXhackse** [comment]
That's okay for me, I am just sorry I didn't manage to complete it as fast as I was expecting.

I am currently trying to find some free time to continue. I just expected it to be easier (probably we all do, when we don't know the structure of a package ;-) ) So thanks a lot for the hints so far.

**Comment by Witiko** [comment]
> probably we all do, when we don't know the structure of a package ;-)

That's a nice way of putting it. 😄 
The package would benefit from splitting the `markdown.dtx` file into a set of smaller files, each with just a few responsibilities.   
If it's difficult for me to contribute new functionality, I can only imagine what new contributors must experience.

**Comment by kalekje** [comment]
I just want to add my "hacky" solution to this: One could pre-read the .md file, store it as a string, stop at the end of the yaml block, and use that info with a lua package like tinyyaml to prase it into a table.

Thanks for this great package.

**Comment by krono** [comment]
Woho!
