### ISSUE TITLE
The HTML manual displays bad outputs and is too hard to use

### ISSUE THREAD

**Issue by quark67** [Witiko/markdown#261]
On http://mirrors.ctan.org/macros/generic/markdown/markdown.html (I don't find the corresponding HTML file on this GitHub project), for exemple on section 2.1.3 (LaTeX), we see the output of the code, and it appears as:
<img width="686" alt="image" src="https://user-images.githubusercontent.com/9338576/216750977-22ebab6b-1060-4abe-8701-3eb04913eaac.png">

Square root and minus sign is very ugly. And it's not an image, but an HTML generated material.

Why don't you provide a PDF manual with the real (nice) output?
<img width="297" alt="image" src="https://user-images.githubusercontent.com/9338576/216751100-0bc063b5-72f8-4b92-b761-00cffc0f8372.png">

Also, I don't find all the options for 

```latex
\begin{markdown*}{...}
```

(Edit: found `hybrid` at 2.2.1.28 (!). But there is no 2.2.1.28 in the table of content in the beginning of the HTML file. And why this `hybrid` is only described for Lua? Why not on 2.2.3.x for LaTeX? On 2.1.3 the "hybrid" is used in the LaTeX exemple)

With a PDF manual with a index, it will be more user friendly to find all relevant information. After all, LaTeX output PDF, not HTML. 

Hope you can correct all this (I know that write a user manual is a pain).

**Comment by Witiko** [comment]
> Square root and minus sign is very ugly. And it's not an image, but an HTML generated material.

I suppose we could use [MathML][1] here.

 [1]: https://www.w3.org/TR/mathml-core/

> And why this `hybrid` is only described for Lua? Why not on 2.2.3.x for LaTeX?

The `hybrid` option is a Lua option. Even though it can also be set from LaTeX, it's not LaTeX-specific.

> Also, I don't find all the options for `\begin{markdown*}{...}`

Which options did you not find?

**Comment by Witiko** [comment]
> With a PDF manual with a index, it will be more user friendly to find all relevant information.

We provide a technical documentation in PDF, which contains an index as well as all the details of the implementation, and an user manual in HTML, which is shorter and contains mostly hands-on examples. However, despite the changes aimed at making the user manual easier to read, it is still affected by the fact that it is automatically generated from the source code of the package.

In the future, we would like to separate the user manual to its own separate document (or set of documents) independent of the Markdown package, see #135 and #184. This should make the user manual more useful and also available in a number of formats. However, we currently don't have any contributors who would be willing to work on this.
