### ISSUE TITLE
Add support for content cherry-picking

### ISSUE THREAD

**Issue by Witiko** [Witiko/markdown#28]
## Introduction
Users typesetting proceedings, almanacs, and other kinds of composite documents from external markdown documents would benefit from an option to cherry-pick only select portions of a markdown document. I am considering adding the `sliceBegin` and `slideEnd` Lua parser options, which would each accept a string in the following format (given in BNF): `{[^|$]ATX_HEADER|^|$}`. The individual values would carry the following meaning:
- `^` – the beginning of the document (the default value of `sliceBegin`),
- `^ATX_HEADER` – the beginning of section `ATX_HEADER`,
- `ATX_HEADER` – corresponds to `^ATX_HEADER` for `sliceBegin` and to `$ATX_HEADER` for `sliceEnd`,
- `$ATX_HEADER` – the end of section `ATX_HEADER`,
- `$` – the end of the document (the default value of `sliceEnd`).

## Examples

Consider the following example document `document.md`:
```md
Chapter 1
========
Some text.

Section 1.1
-----------
Some other text.

Section 1.2
-----------
Yet another text.
```

Below are example outputs of the `\inputMarkdown` macro for various values of the `sliceBegin` and `sliceEnd` options:

***

```tex
\inputMarkdown[sliceBegin=^, sliceEnd=$]{document.md}
```

Chapter 1
========
Some text.

Section 1.1
-----------
Some other text.

Section 1.2
-----------
Yet another text.

***

```tex
\inputMarkdown[sliceBegin=## Section 1.1]{document.md}
```

Section 1.1
-----------
Some other text.

Section 1.2
---------------
Yet another text.

***

```tex
\inputMarkdown[sliceEnd=## Section 1.1]{document.md}
```

Chapter 1
========
Some text.

Section 1.1
-----------
Some other text.

***

```tex
\inputMarkdown[sliceBegin=^# Chapter 1, sliceEnd=^## Section 1.1]{document.md}
```

Chapter 1
=========
Some text.

***

```tex
\inputMarkdown[sliceBegin=^# Chapter 1, sliceEnd=$## Section 1.1]{document.md}
```

Chapter 1
=========
Some text.

Section 1.1
---------------
Some other text.

**Comment by Witiko** [comment]
Another option useful for cherry-picking text from Markdown documents is shifting the heading levels:

```markdown
\inputMarkdown[sliceEnd=## Section 1.1, shiftHeadings=+2]{document.md}
```

### Chapter 1
Some text.

#### Section 1.1
Some other text.

***

```markdown
\inputMarkdown[sliceEnd=## Section 1.1, shiftHeadings=-1]{document.md}
```

# Chapter 1
Some text.

# Section 1.1
Some other text.

**Comment by Witiko** [comment]
It is not unusual to have ambiguous headers in a document. For that reason, it would make sense to allow for multiple-level `ATX_HEADER`s for disambiguation:

***

```tex
\inputMarkdown[sliceBegin=# Chapter 1 ## Section 1.1]{document.md}
```

Section 1.1
-----------
Some other text.

Section 1.2
---------------
Yet another text.

***

Occasinally, a hash sign may appear in a header. For these special occasions we should support escaping the hash sign (`\#`), so that the user can specify such headings in the `sliceBegin` and `sliceEnd` options.

**Comment by dvins** [comment]
This would potentially be another one to sponsor too.
