### ISSUE TITLE
Add TeX Live 2022 historical image

### ISSUE THREAD

**Issue by Witiko** [Witiko/markdown#285]
https://gitlab.com/islandoftex/images/texlive/-/merge_requests/32 moved the `texlive/texlive:latest` image from TeX Live 2022 to TeX Live 2023 and added the `texlive/texlive:TL2022-historic` Docker image. We should introduce a image based on `texlive/texlive:TL2022-historic` to continuous integration.

**Comment by Witiko** [comment]
We may also want to consider dropping support for TeX Live 2020, removing legacy code and revisiting https://github.com/Witiko/markdown/issues/93.

**Comment by vaibhavmishra4g** [comment]
hey could you guide me to fix the issue? i'm really interested in doing it

**Comment by Witiko** [comment]
@vaibhavmishra4g Hello. This issue is blocked by https://github.com/Witiko/markdown/issues/281. Namely, no historic Docker image is provided for TeX Live 2022 at the moment and the current TeX Live 2023 has broken ConTeXt support.

**Comment by Witiko** [comment]
@vaibhavmishra4g Fixed by #295 and will be released as a part of version 2.23.0 tomorrow. Thank you for your offer of help. If you'd like to participate in the development, please let me know. There are [interesting open issues][1] that could use some help. 🙂 

 [1]: https://github.com/Witiko/markdown/issues?q=is%3Aopen+label%3A%22good+first+issue%22%2C%22help+wanted%22
