### ISSUE TITLE
Support for inline footnotes

### ISSUE THREAD

**Issue by michal-h21** [Witiko/markdown#3]
It would be nice to add support for inline footnotes. As usual in Markdown world, several forms exists:

- [Pandoc](http://pandoc.org/MANUAL.html#footnotes): 
> Here is an inline note.^[Inlines notes are easier to write, since
you don't have to pick an identifier and move down to type the
note.]
- [iA Writer](https://ia.net/writer/support/general/markdown-guide):
> Some text with a footnote[^This is the footnote itself.].
- [One variant of PHP Markdown](https://rephrase.net/box/word/footnotes/syntax/):
> I met Jim [^](My old college roommate) at the station.

As Pandoc is the de facto Markdown standard, it seems like the best idea to support this variant.

I've tried to add support by myself, but failed. This is my code:

```
  function self.inline_note(note)
    return function()
      return writer.note(parse_inlines(note))
    end
  end
  -- I've tried two variants of the pattern
  -- local InlineNote = (circumflex * lbracket) * tag / self.inline_note
  local  InlineNote = circumflex * lbracket * C((anyescaped - rbracket)^1) * rbracket / self.inline_note
```
I've added the `InlineNote` to `Inline` grammar. The converted result is:

    \markdownRendererCircumflex{}[footnote text]

Strange is, if I tried to support the iA Writer variand (`[^footnote text]`) with

    InlineNote = lbracket * circumflex * C((anyescaped - rbracket)^1) * rbracket / self.inline_note 

then it works, but this definition causes normal footnotes to fail, so it is not correct as well.

There is also one issue I faced, there are too many local variables in the parsing function, this is why I used `function self.inline_note`, when I tried `local function inline_note`, I've got this runtime error:

> error loading module markdown from file ./markdown.lua:
>        ./markdown.lua:1245: too many local variables (limit is 200) in function at line 413 near '='

This means that it would be quite hard to add more patterns to the parser, maybe the parsing functions should be stored in some table (I used `self`, but dedicated table should be better?).

**Comment by Witiko** [comment]
I am aware that we are currently hitting the local variable limit in the `reader.new` method. The issue can be patched by moving a portion of the LPeg patterns to the scope outside `reader.new`. There is, however, a limit to the number of upvalues as well, so this is not a long-term solution.

Since the users of lunamark would likely benefit from this extension as well, I suggest that you submit your patch for inline footnote support to [the upstream][jgm/lunamark] along with a patch that moves (at least a portion of) the immutable local variables into a hash table.

 [jgm/lunamark]: https://github.com/jgm/lunamark

**Comment by Witiko** [comment]
I am willing to add the feature to this package and propagate it to `lunamark` myself, but I am not yet sure when I'll get to it.

**Comment by Witiko** [comment]
Support for Pandoc inline footnotes is now available as a part of the [`feature-inline-footnotes`](https://github.com/Witiko/markdown/tree/feature-inline-footnotes) branch. I will be merging the branch into `master` as soon as the changes have been merged by [jgm/lunamark](https://github.com/jgm/lunamark). Any testing before the merge will be appreciated.
