### ISSUE TITLE
Unwanted characters in URL inside caption.

### ISSUE THREAD

**Issue by nopria** [Witiko/markdown#311]
Adding the following URL

`\protect<http://bollettinodarte.beniculturali.it/opencms/multimedia/BollettinoArteIt/documents/1481561322323_07_Rodi_36.pdf>`

 inside a figure caption, some additional non-existing characters (`{}`) are rendered

`http://bollettinodarte.beniculturali.it/opencms/multimedia/BollettinoArteIt/documents/1481561322323_{}07_{}Rodi_{}36.pdf`

My preamble contains

```
\usepackage{xurl}

\usepackage[smartEllipses, inlineFootnotes, rawAttribute, fencedCode, hybrid, startNumber=false, tightLists=false, underscores=false,superscripts]{markdown}% "tightLists=false" needed for compatibility with enumitem

\let\markdownRendererStrongEmphasis=\textbf

\markdownSetup{
    renderers = {
        link = {%
            \ifthenelse{\equal{#1}{#2}}{%
                % Handle autolink URI. <https://foo.bar/>
                \url{#2}
            }{%
                \ifthenelse{\equal{mailto:#1}{#2}}{%
                    % Handle autolink e-mail. <john@doe.edu>
                    \textsf{\href{#2}{#1}}
                }{%
                    % Handle labeled link. [label](https://foo.bar/ "title")
                    \ifthenelse{\equal{#4}{href}}{% if "title" value is "href" uses \href instead of \footnote
                        \href{#2}{#1}
                    }{%
                        \ifx\empty#4\empty\else#4: \fi#1\footnote{\url{#2}}
                    }%
                }%
            }%
        }
    }
}

```

**Comment by Witiko** [comment]
@nopria You seem to be using #2. However, quoting from [the user manual][1], #2 is intended for typesetting, whereas #3 is the raw url to be used with commands such as `\url` and `\href`:

 [1]: https://witiko.github.io/markdown/#link-renderer

> The `\markdownRendererLink` macro represents a hyperlink. It receives four arguments: the label, the fully escaped uri that can be directly typeset, the raw uri that can be used outside typesetting, and the title of the link.

Next time, please include a full MWE, so that we can compile and reproduce your problem and better help you.
