### ISSUE TITLE
problem with # sign in url and hyperref

### ISSUE THREAD

**Issue by addyi** [Witiko/markdown#33]
I hade a problem with the # sign in urls and the hyperref package. I asked for help at tex.stackexchange: https://tex.stackexchange.com/questions/418726/markdown-package-problem-with-sign-in-url-and-hyperref

Here the problem in short: 

```
\usepackage[	
		blankBeforeBlockquote,
		blankBeforeCodeFence,
		codeSpans,
		citations,
		definitionLists,
		fencedCode,
		hybrid,
		underscores,
		inlineFootnotes,
		hashEnumerators	]{markdown}

\usepackage{hyperref}

\begin{document}
\begin{markdown}

Here's a link to [a website](https://developer.android.com/training/testing/fundamentals.html#testing-pyramid).  

\end{markdown}
\end{document}
```

If I compile the above code, I get following error message.

> Illegal parameter number in definition of \Hy@tempa.

Ulrike Fischer had a quite nice solution for me. Maybe it is easy for you to incorporate this solution in your package.

Her solution, with a little tweak of mine:

```
{\catcode35=12 [a website](urlwith#sign)}
```

**Comment by Witiko** [comment]
See [my answer](https://tex.stackexchange.com/a/419406/70941) at the TeX Stack Exchange.
