### ISSUE TITLE
Nested ordered lists

### ISSUE THREAD

**Issue by akloeckner** [Witiko/markdown#34]
One feature I am seeking for constantly is nested ordered lists. It seems to me that any list such as 
```
1. test
    1. dodo
    2. gaga
2. more test
```
is always redered exactly as above. What I would like to achieve, is that the indented list is redered as 
```
1. test
    a) dodo
    b) gaga
2. more test
```
I believe LaTeX should do this automatically, but the generated temporary code hardcodes the numbering by `\markdownRendererOlItemWithNumber{1}`.

Is there a way to achive the desired behavior?

And as a side note: I often also would like to have the first level of the enumerated list appear as a), b), c). This is so as to mark alternative options and not a consecutive number of steps to take. It would be perfect, if I could also achieve that...

Thanks for you help!

**Comment by Witiko** [comment]
Hi,

first of, you can disable what you call hardcoded numbering by specifying the `startNumber=false` Lua option. Then the ordered list items will be converted to the `\markdownRendererOlItem` macro and both

```md
1. one
2. two
3. three
```

and

```md
4. one
5. two
6. three
```

will produce the same output.

**Comment by Witiko** [comment]
As for changing the format of the lists, you can use standard LaTeX for that:
```tex
\documentclass{article}
\usepackage[startNumber=false]{markdown}
\begin{document}

\begin{markdown}
1. test
2. more test
\end{markdown}

\begingroup
\renewcommand{\theenumi}{\alph{enumi}}
\begin{markdown}
1. test
2. more test
\end{markdown}
\endgroup

\begin{markdown}
1. test
2. more test
\end{markdown}

\end{document}
```
![screenshot_20180330_211342](https://user-images.githubusercontent.com/603082/38150456-3d4fde44-345f-11e8-9884-d0411f371694.png)

**Comment by akloeckner** [comment]
Thanks @Witiko! 

Just for the afterworld... Note the `startNumber=false` option, which I overlooked at first. It enables the `\theenumi` redefinition and also enables the regular automatic LaTeX numbering schemes.
