### ISSUE TITLE
Superscript and Subscript

### ISSUE THREAD

**Issue by paulhubble** [Witiko/markdown#35]
I am using version 2.5.5 of this package with Overleaf, and I can't for the google of me figure out the syntax for superscript and subscript. Pandoc markdown syntax such as, "water is H\~2\~O" and "21^st^ Century" do not work. The \~ get ignored, and the ^ throws a compile error. Any thoughts?

**Comment by paulhubble** [comment]
I've discovered I can use \textsubscript{} and \textsuperscript{} but the whole point of using markdown is not to have to have latex interrupting the flow of writing and reading. Hopefully there's a way to use pandoc markdown syntax.

**Comment by Witiko** [comment]
> The ~ get ignored, and the ^ throws a compile error.

The characters have a meaning in TeX. The tilde (`~`) represents a non-breaking space and the caret (`^`) represents a math superscript. Example: “See Section~2. $2^4=16$.” If you don't want these symbols to be interpreted by TeX, disable the `hybrid` option you have enabled. After that, the symbols will lose their special meaning; you will also lose the ability to use TeX macros in your markdown documents.

**Comment by Omikhleia** [comment]
Greetings,
I have just made a PR on **lunamark** (on which this project is initially based, if I understand correctly), notably implementing superscript and subscript: https://github.com/jgm/lunamark/pull/36 - Maybe it could help here too?
Regards.

**Comment by Witiko** [comment]
Closed by #162.
