### ISSUE TITLE
File transclusion

### ISSUE THREAD

**Issue by michal-h21** [Witiko/markdown#4]
Recently released iA Writer has interesting extension to Markdown, they call it content blocks. This enables easy inclusion of images, tables, source code and child documents. For example:

```
/Savings Account.csv 'Recent Transactions'
/Example.swift
/Lorem Ipsum.txt
```

would create the table from file `Savings Account.csv`, include `Example.swift` as source code and include contents of `Lorem Ipsum.txt` processed with Markdown. 

More details can be found in [this post](https://ia.net/writer/updates/ia-writer-4?utm_content=buffer79d74&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer), there is also [in depth description](https://github.com/iainc/Markdown-Content-Blocks). 

I guess that it wouldn't be easy to support for example the syntax highlighting and CSV inclusion in all TeX engines, but I like the idea. What do you think?

**Comment by Witiko** [comment]
I am quite fond of the idea to replace the Markdown image tag with something more seamless. It is an easy matter to add experimental support for converting

```markdown
/Savings Account.csv 'Recent Transactions'
/Example.swift
/Lorem Ipsum.txt
http://example.com/minard.jpg (Napoleon’s disastrous Russian campaign of 1812)
/Flowchart.png "Enginering Flowchart"
```
into
```latex
\markdownRendererContentBlockLocal{Savings Account.csv}{Recent Transactions}
\markdownRendererContentBlockLocal{Example.swift}{}
\markdownRendererContentBlockLocal{Lorem Ipsum.txt}{}
\markdownRendererContentBlockOnline{http://example.com/minard.jpg}{Napoleon’s disastrous Russian campaign of 1812}
\markdownRendererContentBlockLocal{Flowchart.png}{Enginering Flowchart}
```
but the real question is how much pre-processing should be done by `lunamark`. Should we produce tables from known formats? If so, we will need to add support for a table extension first. Should we download content referenced by URLs or should this be left to TeX formats?

**Comment by michal-h21** [comment]
I think that `lunamark` should do a basic detection of content types, as there is limited number of supported image types, tables can be contained only in `csv` files, and supported languages are defined [lagnauges.json](https://github.com/iainc/Markdown-Content-Blocks/blob/master/Languages.json).

So, the result could be something like:
 
```
\markdownRendererContentBlockCsv{Savings Account.csv}{Recent Transactions}
\markdownRendererContentBlockSyntaxHighlight{Example.swift}{swift}{}
\markdownRendererContentBlock{Lorem Ipsum.txt}{}
\markdownRendererContentBlockImage{Flowchart.png}{Enginering Flowchart}
```

Regarding tables, I think that `csv` parsers exists for all formats and engines, so it shouldn't be necessary to convert it to Markdown tables. I am not sure how these parsers conform to `csv` standard though. 

Online referenced can be only images. I am not sure whether it's possible to download content from the internet from engines other than LuaTeX, so it it probably should be downloaded by `lunamark`. Maybe the url's can be hashed and images can be saved in the temp directory, which is created anyway. Image hashes can be checked against temp filenames, in order to assure that the image is downloaded only once.

**Comment by Witiko** [comment]
> I think that `lunamark` should do a basic detection of content types, as there is limited number of
> supported image types, tables can be contained only in `csv` files, and supported languages are
> defined [langauges.json](https://github.com/iainc/Markdown-Content-Blocks/blob/master/Languages.json).

It might me a good idea to load all the `Languages.json` files found by `kpathsea` and combine them in a cascading manner. This way, the user may create their own `Languages.json` file in the current folder or in `~/texmf` without completely overriding the `Languages.json` file provided as a part of the TeX distribution.

> Regarding tables, I think that `csv` parsers exists for all formats and engines, so it shouldn't be
> necessary to convert it to Markdown tables. I am not sure how these parsers conform to `csv`
> standard though.

True, but it might still make more sense to parse the CSV and produce table renderer macros specific to the `markdown` package. This way, tables will be typeset consistently regardless of whether they are input as a content block or as a markdown table. Passing the CSV file directly to TeX should be enough for the initial experiments, though.

> Online referenced can be only images. I am not sure whether it's possible to download content from
> the internet from engines other than LuaTeX, so it it probably should be downloaded by `lunamark`.
> Maybe the url's can be hashed and images can be saved in the temp directory, which is created
> anyway. Image hashes can be checked against temp filenames, in order to assure that the image is
> downloaded only once.

We will need to produce the cache filenames by hashing the URLs, since that is the only information we have at disposal while offline.

**Comment by Witiko** [comment]
I am sorry about the wait, I did not have the time to work on the feature until now. The [feature-file-transclusion](https://github.com/Witiko/markdown/tree/feature-file-transclusion) branch should contain all the necessary code. Example LaTeX document:

```tex
\documentclass{article}
\begin{filecontents*}{scientists.md}
Foo bar
\end{filecontents*}
\begin{filecontents*}{scientists.csv}
name,surname,age
Albert,Einstein,133
Marie,Curie,145
Thomas,Edison,165
\end{filecontents*}
\usepackage[contentBlocks,contentBlockPolymorphism]{markdown}
\begin{document}
\begin{markdown}
/scientists.md
/scientists.csv
\end{markdown}
\end{document}
```

I considered implementing URL fetching, but I decided against it in the end, as it is difficult to provide a robust implementation that would fit everybody's needs. The users may easily implement URL fetching themselves:

```tex
\markdownSetup{
  renderers = {
    image = {\includegraphics{\fetchURL{#3}}}
  }
}
```

where `\fetchURL` may expand to a Lua call, `\immediate\write18{wget ...}`, etc.

I will merge and release by the end of the next week. In the meantime, I will be grateful for any feedback.

**Comment by michal-h21** [comment]
That's great, thanks!

I think that

**Comment by Witiko** [comment]
Note that all `Languages.json` files are [loaded and transformed into a chain of tables bound via metatables](https://github.com/Witiko/markdown/blob/feature-file-transclusion/markdown.dtx#L2470). As a result, you may maintain your local `Languages.json` file without altering the `Languages.json` file that comes along with the distribution.

Currently the `Languages.json` file is identical to the one from [iainc/Markdown-Content-Blocks](https://github.com/iainc/Markdown-Content-Blocks). I guess it would make more sense to give an option to change the filename from `Languages.json` to a custom one and distribute various mappings that are compatible with packages such as `listings`, `minted`, or the ConTeXt highlighter. Then again, that's a lot of different `Languages.json` files to maintain, so perhaps it would be best to persuade the package maintainers to distribute their own JSON mappings. I haven't really thought this through yet.

Last thing on my mind: the `contentBlockPolymorphism` is probably going away before the release. It seems superfluous, as we can just transform the input to:
- `\markdownRendererContentBlock{suffix}{raw URL}{URL}{title}`,
- `\markdownRendererContentBlockOnlineImage{suffix}{raw URL}{URL}{title}`, or
- `\markdownRendererContentBlockCode{suffix}{language}{raw URL}{URL}{title}`

and let the user decide whether they want to delegate the `contentBlockOnlineImage` renderer to the `image` renderer and the `contentBlockCode` renderer to the `inputFencedCode` renderer (the default behavior), or whether they want to strip away the extra information and delegate both the `contentBlockOnlineImage` and `contentBlockCode` renderers to the `contentBlock` renderer.

**Comment by Witiko** [comment]
Also the `Languages.json` file is currently CC BY-SA-licensed, so I can't include it in the release. The release version will therefore either ship without a `Languages.json` file, requiring the user to supply one themselves, or it might ship with a number of different `Language.json` files as suggested above.

**Comment by michal-h21** [comment]
It also seems that many languages are missing from the `Language.json` - I've extracted list of 90 languages supported by `Listings` package, only 25 of them were found there. Even major ones like `PHP` or `C` seems missing. I guess that it is because the name and the extension are equal. 

Anyway, it seems like a good idea to use different JSON files for each particular syntax highlighter, as they may use different names for one language.
