### ISSUE TITLE
Word "true" rendered at the end of some elements

### ISSUE THREAD

**Issue by l0th3r** [Witiko/markdown#446]
Hi, I am really new to Tex, LaTex and LuaTex.

While rendering a list in markdown. The word "true" is rendered under the titles.

Do you have any idea what it is that could cause this word to be rendered ?
Thank you in advance for the help.

Markdown file content:
``` markdown
## TITLE
1. **ELEMENT**
    1. Element
    2. Element
    3. Element
2. **ELEMENT**
    1. Element
    2. Element
3. **ELEMENT**
    1. Element
    2. Element
4. **ELEMENT**
    1. Element
    2. Element
    3. Element
5. **ELEMENT**
    1. Element
    2. Element
```
PDF render:
![Screenshot from 2024-06-10 14-48-41](https://github.com/Witiko/markdown/assets/58365407/92b3d58e-bc23-43fd-a4c3-2ccfa2308574)

**Comment by Witiko** [comment]
Hi and thanks for using the Markdown package. This seems strange, can you please share your `.tex` document here?

**Comment by Witiko** [comment]
@l0th3r Have you updated the whole markdown package, including the file `markdownthemewitiko_markdown_defaults.sty`?
