### ISSUE TITLE
Review compatibility of LaTeX dependencies with PDF tagging

### ISSUE THREAD

**Issue by Witiko** [Witiko/markdown#466]
During [their TUG talk][1], @u-fischer mentioned a [list][2] of LaTeX packages (and classes) that are (in)compatible with the PDF tagging project. We should review the list, compare it with the LaTeX dependencies of the Markdown package (see [technical documentation][3], Section 1.1.3), and see if we can remove or replace any packages that are not listed as "compatible".

In the example markdown documents for the PDF tagging workshops at TUG 2023 and 2024, there is the following code:

``` tex
\usepackage[tightLists=false,
            fencedCode %%don't load paralist ...
            ]{markdown}
```

This indicates that the `paralist` package is a part of the problem.

 [1]: https://tug.org/tug2024/slides/fischer-tagging24.pdf
 [2]: https://latex3.github.io/tagging-project/tagging-status/
 [3]: https://mirrors.ctan.org/macros/generic/markdown/markdown.pdf

**Comment by Witiko** [comment]
In the list, the markdown package is listed as "unknown" and "needs tests". I wonder if we can do anything about that?!

**Comment by u-fischer** [comment]
I can change that to "partially-compatible" with a comment and add the workshop file as a first test file.  But as there are lots of options it really needs more tests and examples. (And you can write "in her TUG talk ...", it is not a secret that I'm a woman.)

**Comment by Witiko** [comment]
> But as there are lots of options it really needs more tests and examples.

Most options enable syntax extensions. These produce renderer commands that are handed over to various LaTeX packages unless the commands are redefined by users. All dependencies are listed in Section 1.1 of [the technical documentation][1]. The default renderer commands are defined in Section 3.3.4 of the same document. Most incompatibilities should be visible at a glance and due to our use of an outdated LaTeX package. We do very little low-level TeX stuff or patching on our own.

I am happy to write tests and examples. As I understand it, this was one of the topic of this year's LaTeX developers' workshop. Sadly, I could not attend it but I am happy to go through the materials on my own. However, I will appreciate directions.

> And you can write "in her TUG talk ...", it is not a secret that I'm a woman.

I have use the singular they for possessives in my writing for the past ~15 years, long before it was the politically correct thing to do. I am sorry if this feels somewhat impersonal.

 [1]: https://mirrors.ctan.org/macros/generic/markdown/markdown.html

**Comment by Witiko** [comment]
> This indicates that the `paralist` package is a part of the problem.

Earlier today, I happened to glance on my notes from the TUG 2023 workshop, which indicate that our use of packages `enumitem` and `fancyvrb` for the default renderer prototypes was also a problem, not just `paralist`.

Looking at https://latex3.github.io/tagging-project/tagging-status/, I can see that `enumitem` is already partially-compatible, which may indicate that it will eventually be fully compatible. In that case, we should simply migrate our uses of `paralist` to `enumitem`.

By contrast, `fancyvrb` is listed as incompatible but we don't have a suitable replacement for the `minted` package at the moment, which uses `fancyvrb` as its backend; therefore, it's unclear what should be done about our use of the `fancyvrb` package, if anything.

**Comment by u-fischer** [comment]
* I just added a first support for fancyvrb to our develop branch. I also made  a test with minted and it seemed to work (but I did not test all commands, mainly the environment).

* we are working on the enumitem replacement but I didn't look at paralist yet. 

* regarding tabularray you should ask the maintainer, e.g. by commenting to this issue https://github.com/lvjr/tabularray/issues/27. That is not something we can tag from the outside. 

* there is not difference between soul and soututf8. We merged the packages. I haven't looked yet why it errors (probably some box nesting). With the (tagging-wise recommended) lualatex I wouldn't use it anyway but lua-ul instead.

**Comment by Witiko** [comment]
> I just added a first support for fancyvrb to our develop branch. I also made a test with minted and it seemed to work (but I did not test all commands, mainly the environment).

That's good news! I won't worry about it for the moment, then.

> we are working on the enumitem replacement but I didn't look at paralist yet.

When you say "replacement", do you mean external patches to the existing packages or new packages?

> regarding tabularray you should ask the maintainer, e.g. by commenting to this issue https://github.com/lvjr/tabularray/issues/27. That is not something we can tag from the outside.

It seems to me that the maintainer has made some progress. In https://github.com/lvjr/tabularray/issues/27#issue-934526294, you asked them for "places to inject tagging code at the begin and end of a cell and of a row", which they added in https://github.com/lvjr/tabularray/issues/197 and demonstrated in https://github.com/lvjr/tabularray/issues/27#issuecomment-1426593763. I am not sure about the other two requirements from https://github.com/lvjr/tabularray/issues/27#issue-934526294 (ways to identify header rows, header columns, and lines).

I submitted a question to the maintainer in https://github.com/lvjr/tabularray/issues/27#issuecomment-2400501014

> there is not difference between soul and soututf8. We merged the packages. I haven't looked yet why it errors (probably some box nesting).

Then this should be a non-issue.

> With the (tagging-wise recommended) lualatex I wouldn't use it anyway but lua-ul instead.

Thanks for the tip. We can use the package **lua-ul** with LuaLaTeX instead of the package **soul**. However, the package **lua-ul** is also marked as currently-incompatible at [[tagging-status]][1]; should that bother me?

 [1]: https://latex3.github.io/tagging-project/tagging-status/

**Comment by u-fischer** [comment]
lua-ul doesn't error. It only doesn't tag anything. 

And regarind soul: Regardless how easy or complicated it is to tag it, someone has too look into the code and create test files etc. That costs time and it is currently not a high priority problem.

**Comment by Witiko** [comment]
> * ✅ We should remove the `\csvautotabular` macro from the default renderer prototypes for iA Writer content blocks.
> * 🤔 I wonder if there are any suitable replacements compatible with PDF tagging that we might use instead?

Let's table this for the moment (pun intended), since there is potential for the package **tabularray** moving in the direction of PDF tagging support as discussed in https://github.com/lvjr/tabularray/issues/27#issuecomment-2400954609.

To wrap up, here are the changes that I am comfortable bringing to the next release of the Markdown package:

1. In LuaLaTeX, use package **lua-ul** for strike-through renderer prototypes instead of package **soul**(**utf8**).
2. Use package **enumitem** for tight and fancy lists instead of package **paralist**.

The second change is major. We should still keep definitions for the package **paralist** for users who explicitly load it and highlight it in the release notes / changelog.

**Comment by Witiko** [comment]
To wrap up, here are the changes that I am comfortable bringing to the next release of the Markdown package:

1. In LuaLaTeX, use package **lua-ul** for strike-through renderer prototypes instead of package **soul**(**utf8**).
2. Use package **enumitem** for tight and fancy lists instead of package **paralist**.

The second change is major. We should still keep definitions for the package **paralist** for users who explicitly load it and highlight it in the release notes / changelog.

**Comment by Witiko** [comment]
The changes from #512 are still significant and while the Markdown package makes no guarantees about the default renderer prototype definitions, it would be beneficial to provide a controlled way for users to delay the update of these definitions without delaying the entire package update.

Therefore, we may want to only use these new definitions for [the `experimental` version][2] or when any document property with the prefix `testphase/` is set. See also Section 4.3 of the document [`documentmetadata-support-code.pdf`](https://mirrors.ctan.org/macros/latex/required/latex-lab/documentmetadata-support-code.pdf) and the discussion with @TeXhackse on [our Matrix.org server][1].

This way, we won't rock the boat as much for users who are more interested in stable defaults and less in PDF tagging. Furthermore, loading new definitions for any test phase also exposes (some) experimental definitions to more users, which means more user feedback, which is good.

 [1]: https://matrix.to/#/!UeAwznpYwwsinVTetR:matrix.org/$TTc-m7B5NSdsLBNNyIuFWQ-u2nOZ03lJ5js88hnyFiU?via=matrix.org&via=im.f3l.de
 [2]: https://github.com/Witiko/markdown/discussions/514
