### ISSUE TITLE
Math display mode \[ \] not recognized

### ISSUE THREAD

**Issue by axsk** [Witiko/markdown#47]
Using `\usepackage[hybrid]{markdown}`

`\begin{equation}` is recognized, wheres the shorthand `\[` is not :(

**Comment by Witiko** [comment]
Have you tried `\\[`? The square bracket is a part of the Markdown syntax, so a single backslash only escapes it into a regular bracket.

**Comment by Witiko** [comment]
Closing due to a month of inactivity.

**Comment by axsk** [comment]
Oh sry, yes \\[ worked :)
