### ISSUE TITLE
URL Parsing

### ISSUE THREAD

**Issue by l0th3r** [Witiko/markdown#475]
Hi,

Thank you for your work on this package. And for your care when it comes to issues.

I encountered an issue while rendering a url with special characters.
In french web some articles/page names have some `é` `è` `à` characters for example.
Those characters are encoded in UTF-8 such as `é` = `%C3%A9`

How can I sanitize the content of the markdown files for them not to be interpreted as Tex ?

Content of the markdown file:
```
## Organisation
L'organisation doit suivre une logique [récursive](https://fr.wikipedia.org/wiki/R%C3%A9cursivit%C3%A9).
```
*I used `\markdownInput{file.md}`*

Rendered link:
![image](https://github.com/user-attachments/assets/211a8bff-2619-4700-a74e-1f22fc32521c)

I already tried this before markdown input:
```
\catcode`\$=12
\catcode`\&=12
\catcode`\#=12
\catcode`\^=12
\catcode`\_=12
\catcode`\~=12
\catcode`\%=12
```

Thank you in advance for your answer !

**Comment by Witiko** [comment]
Hi, thanks for using the Markdown package!

> How can I sanitize the content of the markdown files for them not to be interpreted as TeX?

They are not interpreted as TeX. Namely, the percent signs are deactivated when using the `\markdownInput` command. The issue would be with the default renderers and how they process the URL.

Here is the TeX output of your above example document:

``` tex
\markdownRendererDocumentBegin
\markdownRendererSectionBegin
\markdownRendererSectionBegin
\markdownRendererHeadingTwo{Organisation}\markdownRendererInterblockSeparator
{}L'organisation doit suivre une logique \markdownRendererLink{récursive}{https://fr.wikipedia.org/wiki/R\markdownRendererPercentSign{}C3\markdownRendererPercentSign{}A9cursivit\markdownRendererPercentSign{}C3\markdownRendererPercentSign{}A9}{https://fr.wikipedia.org/wiki/R%C3%A9cursivit%C3%A9}{}.
\markdownRendererSectionEnd 
\markdownRendererSectionEnd \markdownRendererDocumentEnd
```

You should try and redefine the command `\markdownRendererLink` to produce a better hyperlink using the arguments `#1` (the text `récursive`) and `#3` (the URL `https://fr.wikipedia.org/wiki/R%C3%A9cursivit%C3%A9`). For example:

``` tex
\documentclass{article}
\usepackage{markdown}
\markdownSetup {
  renderers = {
    link = {%
      \href{#3}{#1}%
    },
  }
}
\usepackage{hyperref}
\begin{document}
\begin{markdown}
## Organisation
L'organisation doit suivre une logique [récursive](https://fr.wikipedia.org/wiki/R%C3%A9cursivit%C3%A9).
\end{markdown}
\end{document}
```

![image](https://github.com/user-attachments/assets/0a50db56-bc3f-4bee-aca1-5ae5d90ff311)

However, we also seem to produce functional hyperlinks with the default renderers:

``` tex
\documentclass{article}
\usepackage{markdown}
\usepackage{hyperref}
\begin{document}
\begin{markdown}
## Organisation
L'organisation doit suivre une logique [récursive](https://fr.wikipedia.org/wiki/R%C3%A9cursivit%C3%A9).
\end{markdown}
\end{document}
```

![image](https://github.com/user-attachments/assets/8d3b625c-1ce5-44b8-85b0-ae62ce24e92a)

Therefore, it's unclear to me how you arrived at your result. Can you share an example TeX document that I can compile?

Furthermore, what version of the Markdown package do you use? You should see a line such as `Package: markdown 2024-07-01 v3.6.1-17-gf57d31e7 markdown renderer` in the `.log` file that is produced when you compile your example document.

**Comment by Witiko** [comment]
> So yes I was already overriding the render of the hyperlinks using this tho:
> 
> ```
> \global\def\markdownRendererLink#1#2#3#4{
>   \href{#2}{#1}
> }
> ```

Use the argument `#3` instead of `#2`. As you can see in https://github.com/Witiko/markdown/issues/475#issuecomment-2283914437, `#2` contains the URL text for typesetting with special symbols replaced with renderer commands, whereas `#3` contains the raw URL text.

**Comment by Witiko** [comment]
Happy to help!
