### ISSUE TITLE
Make enumerators before headers optional

### ISSUE THREAD

**Issue by Schnaffon** [Witiko/markdown#48]
I would like titles to not begin with numbers.
I didn't find a way to achieve this reading through the documentation. Would that be possible ? 

Here is an example : 

```
\begin{markdown}
## H1
\end{markdown}
```

Gives this : 

# 1 H1

Where I'd like 

# H1

**Comment by Witiko** [comment]
Hello, you can achieve this in LaTeX. The Markdown package is not terribly concerned with formatting, it mostly just translates Markdown to LaTeX. To specify that no headings should be numbered, put `\setcounter{secnumdepth}{-1}` at the beginning of your LaTeX document.

**Comment by Schnaffon** [comment]
It works wonders !

Thank you
