### ISSUE TITLE
Compilation errors using MiKTeX and lualatex on Windows

### ISSUE THREAD

**Issue by l0th3r** [Witiko/markdown#492]
Hi,
I am new to Tex and LaTex, especially on Windows.

Recently I needed to be able to compile a project I had on Linux, on Windows.
(never done Tex on Windows before)

On Linux, I was using a [portable install](https://witiko.github.io/markdown/#portable-installation) of the markdown package.
Linux compilation command: `lualatex --shell-escape -interaction=nonstopmode --output-directory=_build main.tex`
(0 error and PDF file content is as expected)

Windows installation process:
- Installed [MiKTeX latest version](https://miktex.org/download).
- Started  `MiKTeX Console` program
    - Chose `https://ctan.mines-albi.fr` as package repository
    - Checked for updates and Installed updates, restart program
    - Installed the `markdown` package
- Removed all files from the portable installation in my project directory

Executed in the directory with *powershell:* `lualatex --shell-escape -interaction=nonstopmode --output-directory=_build main.tex`
Some dialog window showed up to ask to install some packages and said yes to all.
(6 errors and no PDF file produced)

Errors:
``` log
! Undefined control sequence.
\markdownOptionOutputDir ->Z:\shared 
                                     \testTEx \_build 
l.6 \end{markdown}
                
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

! Undefined control sequence.
\markdownOptionOutputDir ->Z:\shared \testTEx 
                                              \_build 
l.6 \end{markdown}
                
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

! Undefined control sequence.
\markdownOptionOutputDir ...ared \testTEx \_build 
                                                  
l.6 \end{markdown}
                
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

! You can't use `\endgroup' after \the.
<argument> \endgroup 
          
l.6 \end{markdown}
                
I'm forgetting what you said and using zero instead.


! Package markdown Error: Markdown file \markdownOptionOutputDir
(markdown)                /\markdownOptionInputTempFileName  does not exist

Type <return> to continue.
 ...                                              
                                                  
l.6 \end{markdown}
                

LaTeX does not know anything more about this error, sorry.

Try typing <return> to proceed.
If that doesn't work, type X <return> to quit.



! LaTeX Error: \begin{markdown} on input line 4 ended by \end{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.7 \end{document}
                
Your command was ignored.
Type  I <command> <return>  to replace it with another command,
or  <return>  to continue without it.
```

[Complete log file](https://github.com/user-attachments/files/16796914/main.log)

main.tex:
``` latex
\documentclass{article}
\usepackage{markdown}
\begin{document}
\begin{markdown}
Hello *world*!
\end{markdown}
\end{document}
```

> Also tried with the `pdflatex` command but similar errors aswell.

Thanks in advance for taking the time to answer.

**Comment by Witiko** [comment]
This is an interesting Windows-specific bug. You should be able to hotfix it by typing `\def\markdownOptionOutputDir{_build}` above `\usepackage{markdown}`. The proper fix is to deactivate all characters in the output dir macro. We may also need to apply the fix in the [Witiko/lt3luabridge](https://github.com/Witiko/lt3luabridge) repository.

**Comment by Witiko** [comment]
Apparently, your file `UnicodeData.txt` contains something that luaotfload cannot parse. Can you take a peek what's inside your file? Mine starts like this:

```
0000;<control>;Cc;0;BN;;;;;N;NULL;;;;
0001;<control>;Cc;0;BN;;;;;N;START OF HEADING;;;;
0002;<control>;Cc;0;BN;;;;;N;START OF TEXT;;;;
0003;<control>;Cc;0;BN;;;;;N;END OF TEXT;;;;
0004;<control>;Cc;0;BN;;;;;N;END OF TRANSMISSION;;;;
0005;<control>;Cc;0;BN;;;;;N;ENQUIRY;;;;
```

**Comment by Witiko** [comment]
You can hotfix the issue by renaming the file `UnicodeData.txt` to e.g. `UnicodeDataMarkdown.txt` and replacing all occurences of `UnicodeData.txt` in `markdown.lua` with the new name.

**Comment by Witiko** [comment]
I will release version 3.7.0, which includes #486, later today. In this version, `markdown.lua` is renamed to `markdown-parser.lua`, so you would need to apply your changes there.

**Comment by Witiko** [comment]
> Do you mean from my part ? Could it be coming from me ?

Potentially, depending on how you downloaded it. For example, if you opened the file in your browser and then copy-and-pasted its contents into the Notepad and saved, this would have saved the file with an incorrect encoding.

**Comment by Witiko** [comment]
I am happy to help. However, let's keep this ticket open, please. https://github.com/Witiko/markdown/issues/492#issue-2493954661 and https://github.com/Witiko/markdown/issues/492#issuecomment-2317900619 mention a bug that should be fixed before closing the ticket.
