### ISSUE TITLE
How can I have two separated quotes?

### ISSUE THREAD

**Issue by kiryph** [Witiko/markdown#5]
If I want to separate two quotes, I usually insert into my markdown files an empty html comment `<!-- -->`.

For example
```markdown
> quote 1
<!-- -->
> quote 2
```
This will give me
> quote 1

> quote 2

How can I do this in my latex document?

```tex
\documentclass{article}
\usepackage{markdown}

\begin{document}
\begin{markdown}
> quote 1
<!-- -->
> quote 2
\end{markdown}
\end{document}
```

My current workaround is

```tex
\documentclass{article}
\usepackage{markdown}

\begin{document}
\end{markdown}
> quote 1
\end{markdown}
\begin{markdown}
> quote 2
\end{markdown}
\end{document}
```
However, I would prefer to have a consistent experience of my markdown data. I do not like to adapt it for a tex file inclusion.

**Comment by Witiko** [comment]
This currently isn't possible, since the package does not parse HTML. You may insert `{}` if you are using the hybrid mode:

```latex
\usepackage[hybrid]{markdown}
[...]
\begin{markdown}
> quote 1

{}

> quote 2 
\end{markdown}
```
but that is about the extent of it.

**Comment by kiryph** [comment]
Thanks for your answer. Your suggestion is better, but I still have to modify my markdown file.

Well, adding HTML parsing would help, but you have to say if this is feasible at all.

On the other hand you could offer a possibility to choose a markdown implementation which would give the author the choice how this handled.

For instance the http://spec.commonmark.org/0.27/#example-203 allows to to uses an empty line to separate two quotes. A list of commonmark implementations can be found here https://github.com/jgm/CommonMark/wiki/List-of-CommonMark-Implementations.

**Comment by Witiko** [comment]
Since the original Lua package from which this project was forked supports HTML parsing, it is definitely feasible. I do not wish to have HTML parsing on by default, since the host markup it TeX, not HTML, but I can add basic HTML support as a syntax extension.

This package also supports several options for controlling how various Markdown edge cases are handled (the `blankBeforeBlockquote`, `blankBeforeCodeFence`, and `blankBeforeHeading` options). I can add a `breakableBlockquotes` one as well.

I will give it a closer look next week.

**Comment by Witiko** [comment]
I need to do a bit of refactoring (see <https://github.com/Witiko/markdown/tree/upstream-refactoring>) before adding new features. I should be finished with it before the end of the year.

**Comment by Witiko** [comment]
The current development version of the package supports HTML elements, entities, instructions, and comments. This means that typesetting the following LaTeX document:
```latex
\documentclass{article}
\usepackage[html]{markdown}
\begin{document}
\begin{markdown}
> quote 1

<!-- -->

> quote 2
\end{markdown}
\end{document}
```
will yield
>quote 1



>quote 2

The update should go live by the end of the week.

**Comment by Witiko** [comment]
I have also implemented the second suggestion. Typesetting the following document:

```latex
\documentclass{article}
\usepackage[breakableBlockquotes]{markdown}
\begin{document}
\begin{markdown}
> quote 1

> quote 2
\end{markdown}
\end{document}
```

will produce the same output as above.

**Comment by sami10007** [comment]
Is this implemented in the current code base? - - I get `! Package keyval Error: breakableBlockquotes undefined.` in Debian 8.7 with TeXLive 2016.

**Comment by Witiko** [comment]
You are likely using an out-of-date version of the package (the `breakableBlockquotes` option was added in [v2.3.0](https://github.com/Witiko/markdown/releases/tag/2.3.0) from January). The option was not available in the version that shipped with base TeX Live, although it should be available if you update your TeX Live. I am unaware of how often the Debian maintainers repackage TeX Live.
