### ISSUE TITLE
\begin{markdown} env not working with latex

### ISSUE THREAD

**Issue by boyoungzheng** [Witiko/markdown#51]
In `document.tex`:

```latex
\documentclass{article}
\usepackage{markdown}
\begin{document}
	\begin{markdown}
		Hello *world*!
	\end{markdown}
\end{document}
```

Either `pdflatex --shell-escape document.tex` or `lualatex document.tex`results in `document.pdf`

```
Hello *world*!
```

But if I try

```latex
\documentclass{article}
\usepackage{markdown}
\begin{document}
\markdownInput{document.md}
\end{document}
```

with`"Hello *world*!"` written in  `document.md` , both `pdflatex` and `lualatex` work pretty well rendering

Hello *world*!

My sys info:
```bash
$ pdflatex --version
pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019)
kpathsea version 6.3.1
Copyright 2019 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.36; using libpng 1.6.36
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.01
$ lualatex --version
This is LuaTeX, Version 1.10.0 (TeX Live 2019)
```

**Comment by boyoungzheng** [comment]
MacOS 10.14.5

**Comment by boyoungzheng** [comment]
(Irrelevant. Maybe create a new issue?) Another thing I want to point out is that it seems I cannot produce `**.markdown.out` file for those `**.tex` whose name contains space.

**Comment by Witiko** [comment]
> […] Either `pdflatex --shell-escape document.tex` or `lualatex document.tex` results in `document.pdf` […]

This is because `Hello *world*!` is indented in your document, so it is recognized as a code block. As a general rule, the markdown package does not strip any indentation from the document. Therefore even the following document would produce `Hello *world!*` rather than Hello *world!*:

```md
\documentclass{article}
\usepackage{markdown}
\begin{document}
	\begin{markdown}
	Hello *world*!
	\end{markdown}
\end{document}
```

For the correct output, your document needs to look as follows:

```md
\documentclass{article}
\usepackage{markdown}
\begin{document}
	\begin{markdown}
Hello *world*!
	\end{markdown}
\end{document}
```

**Comment by Witiko** [comment]
> Another thing I want to point out is that it seems I cannot produce `**.markdown.out` file for those `**.tex` whose name contains space.

This is known and [documented](http://mirrors.ctan.org/macros/generic/markdown/markdown.pdf):

> The `\markdownOptionOutputTempFileName` macro sets the filename of the temporary output file that is created during the conversion from markdown to plain TEX in `\markdownMode` other than 2. It defaults to `\jobname.markdown.out`. The same limitations apply here as in the case of the `\markdownOptionHelperScriptFileName` macro.
>
> […]
>
> The expansion of this macro must not contain quotation marks (`"`) or backslash symbols (`\`). Mind that TEX engines tend to put quotation marks around `\jobname`, when it contains spaces.

**Comment by boyoungzheng** [comment]
Thank you for your reply. I am closing the issue now.

**Summary:** No indentation for `markdown` environment. Otherwise, it will be recognized as a code block.

**Comment by Witiko** [comment]
Note that although the lack of support for spaces in filenames is known and documented, it is a shortcoming that would be nice to fix.

**Comment by obskyr** [comment]
Would a fix for this be as simple as chomping `"` from the start and end of the job name?

**Comment by Witiko** [comment]
> Would a fix for this be as simple as chomping `"` from the start and end of the job name?

Possibly, though there are a lot of moving parts involved and I haven’t had a chance to dig into it. If this is important to you, could you please open a separate issue to track it?

> I've been working on a template for writing novels in LaTeX and Markdown, and it’d be nice not to have to tell my users they can’t use spaces in their filenames!

In the meantime, you can work around this by redefining `\markdownOptionOutputDir` and `\markdownOptionCacheDir`, so that they don't use `\jobname`.
