### ISSUE TITLE
Incorrect vertical spaces between list elements

### ISSUE THREAD

**Issue by pagiraud** [Witiko/markdown#52]
Hi, thanks to all for this extension! It's wonderful. Nevertheless, I've got a problem with it.
Here's a MWE : 
```
\documentclass{report}
\usepackage{markdown}
\usepackage{lipsum}
\begin{document}
\begin{itemize}
	\item \lipsum[1][1]
	\item \lipsum[1][2]
	\item \lipsum[1][3]
\end{itemize}
\begin{markdown*}{hybrid}
- \lipsum[1][1]
- \lipsum[1][2]
- \lipsum[1][3]
\end{markdown*}
\end{document}
```
The space between list elements is not the same outside and inside the markdown environment. I'm using Lualatex with Texlive 2018.20190227 (stock Texlive from Kubuntu 19.04).

**Comment by Witiko** [comment]
Hello, @pagiraud,

the Markdown package distinguishes between tight and multiparagraph list elements. For tight list elements, the default LaTeX renderer uses the paralist package. You can either disable this behavior using `\usepackage[tightLists=false]{markdown}`, or you can rewrite your markdown document as follows:

```markdown
- \lipsum[1][1]

- \lipsum[1][2]

- \lipsum[1][3]
```
In both cases, you will get the requested result.

**Comment by pagiraud** [comment]
Thanks for your reply. I now get the expected result, but I don't think the current approach in the package is optimal.

I discovered letting a blank line between list elements was correct markdown syntax generating slightly different HTML code, and I'm grateful you made me aware of this possibility. But, I would suggest that the most common markdown syntax for lists (without blank lines) be coherent with the default LaTeX output (wide list elements). It would only mean to make  `tightLists=false` the default.

What do you think ?

**Comment by Witiko** [comment]
Some may consider the behavior of `tightLists=false` less surprising and more consistent with the behavior of LaTeX, whereas others may expect LaTeX to produce similar output to HTML. I don't have a strong preference, but I am more leaning with the latter crowd.

**Comment by pagiraud** [comment]
Indeed, it is possible to find valuable arguments on both sides. As a consequence, I close this bug. Thank you for the work on this package and for your answers.
**Summary: leave a blank line between list items or use `\usepackage[tightLists=false]{markdown}` to get the default LaTeX list appearance (wide).**
