### ISSUE TITLE
Number of spaces for nested lists

### ISSUE THREAD

**Issue by jbriales** [Witiko/markdown#55]
It seems currently nested lists in Markdown only recognize as deeper levels those which are 4 spaces (or 1 tab) deep?

e.g.
```
- foo
  - bar
    - quz
```

is rendered for me like this in Latex:

- foo
- bar
  - quz

Is that the expected behavior?
Is there any way to specify the nr of spaces to expect for new list levels? I use 2 everywhere :)

**Comment by Witiko** [comment]
Yes, standard Markdown requires exactly four spaces or one tab, see the spec:

> List items may consist of multiple paragraphs. Each subsequent paragraph in a list item must be indented by either 4 spaces or one tab: […]

There is currently no option to change the default. It would be a fairly straightforward addition, but you would be writing non-portable markdown code. As a rule of a thumb, options are for behavior that is ambiguous and differs between different implementations of Markdown, i.e. I would be reluctant to add support for this behavior.

**Comment by Witiko** [comment]
Due to two weeks of inactivity, I am closing this issue.  
If there are other comments, I can reopen.
