### ISSUE TITLE
User manual

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [Witiko/markdown#56]
Is the [user manual](http://ctan.math.illinois.edu/macros/generic/markdown/markdown.html) hosted in this repo? 

I could be wrong, but shouldn't `document.tex` be `hello.tex` below?

<img width="685" alt="Screen Shot 2020-02-23 at 12 19 15 PM" src="https://user-images.githubusercontent.com/1993919/75116481-dc273080-5636-11ea-98dc-c2c466c6ab42.png">

**Comment by Witiko** [comment]
> Is the [user manual](http://ctan.math.illinois.edu/macros/generic/markdown/markdown.html) hosted in this repo?

The user manual is produced from file `markdown.dtx` in the repo, but it is hosted on [CTAN](https://ctan.org/pkg/markdown).

> I could be wrong, but shouldn't `document.tex` be `hello.tex` below?

See Section 1.3.1. First, you create `document.tex` that loads the Markdown package and then inputs `hello.tex`. Next, you create `hello.tex` that contains the converted markdown document.

**Comment by Witiko** [comment]
Due to two weeks of inactivity, I am closing this issue.
If there are other comments, I can reopen.
