### ISSUE TITLE
MacTeX ! Package markdown Error: I can not access the shell.

### ISSUE THREAD

**Issue by mwalz** [Witiko/markdown#6]
Hello, 

I'm using MacTeX and installed the mardown package via `tlmgr install markdown`

When I attempt to print a simple PDF with embedded markdown, I receive and error:
`! Package markdown Error: I can not access the shell.`

I've been searching for an answer in any similar projects, but have not found anything helpful. Do you have any suggestions?

Thank you!

**Comment by mwalz** [comment]
Apologies, the error was due to the execution method. It was running from within another problem. I included the `--shell-escape` switch and it executes without immediate errors.

A different problem has emerged. The embedded markdown is replaced with `Script file report.markdown.lua not found` in the document.

**Comment by Witiko** [comment]
Hello,

would you please construct a minimal example that exhibits this error, convert it to a PDF, and post all the files that are generated here (along with all the auxiliary files such as `report.log`)?

**Comment by mwalz** [comment]
Hello,

Thank you for the response. 

I have a project that runs Latex via a shell command:  `xelatex --shell-escape -output-directory=/tmp vehicle-session-summary.tex`

The output is directed to a specific directory and all the corresponding files are written to /tmp as expected, *except* for the `markdown.out` file, which is written into the directory where the script is called from. 

My problem appears to be that `markdown.out` does not follow the output-directory defined in the command line. I am assuming I am missing a switch to define the behavior.

[vehicle-summary-tex-files.zip](https://github.com/Witiko/markdown/files/647271/vehicle-summary-tex-files.zip)

**Comment by mwalz** [comment]
For further clarity the attached zip contains the input .tex file and the `markdown.out` file that is generated in the same directory. The files in the pervious zip are written to the `tmp` folder per the `output-directory` parameter.

[vehicle-summary-input-files.zip](https://github.com/Witiko/markdown/files/647311/vehicle-summary-input-files.zip)

**Comment by Witiko** [comment]
The issue is due to your using the `-output-directory` option. As a result, XeTeX stores all output files in the `/tmp` directory. However, the shell (which is invoked to process the Markdown input) runs in the current directory (rather than the `output-directory`) and fails, because it cannot find the `*.markdown.lua` file. The `*.markdown.out` file is a proof of this, since it gets created by the shell in the current rather than in the output directory. This [appears to be a known issue](http://tex.stackexchange.com/q/136012/70941) with packages that rely on shell access.

The obvious workaround is to omit the `-output-directory` option. The stack exchange thread linked above suggests the use of environmental variables to communicate the `-output-directory` to the script, although this is not a portable solution.

**Comment by Witiko** [comment]
You may also use the following patch to arrive at the desired behaviour:

``` diff
diff --git a/markdown.dtx b/markdown.dtx
index 12b4a54..0e64393 100644
--- a/markdown.dtx
+++ b/markdown.dtx
@@ -3741,7 +3741,7 @@ local convert = md.new(\markdownLuaOptions)
   \markdownInfo{Executing a helper Lua script from the file
     "\markdownOptionHelperScriptFileName" and storing the result in the
     file "\markdownOptionOutputTempFileName"}%
-  \markdownExecute{texlua "\markdownOptionHelperScriptFileName" >
+  \markdownExecute{cd /tmp/; texlua "\markdownOptionHelperScriptFileName" >
     "\markdownOptionOutputTempFileName"}%
 %    \end{macrocode}
 % \m{input} the generated \m{markdownOptionOutputTempFileName} file.
```

**Comment by Witiko** [comment]
I am reopening this, since adding an `outputDir` plain TeX option seems feasible.

**Comment by Witiko** [comment]
Since c1a39727fe0a7a466b146fd6645b51b23044d994, the package properly supports the `-output-directory` option. You need to indicate the output directory in the LaTeX document in addition to the command line:
```latex
\usepackage[outputDir=/tmp]{markdown}
```
