### ISSUE TITLE
list format via enumitem

### ISSUE THREAD

**Issue by lululxvi** [Witiko/markdown#63]
I am using `enumitem` to format my lists: compact and small leftmargin (`\setlist{leftmargin=1.25em, nosep}`). But this doesn't work for lists defined in `markdown`. As mentioned in #2, `markdown` uses `paralist compactitem` to render lists, is this right? Is it possible to use `enumitem` for lists defiend in `markdown`? Thanks.

Another question: how can I use `hyperref` for links?

**Comment by Witiko** [comment]
> I am using `enumitem` to format my lists: compact and small leftmargin (`\setlist{leftmargin=1.25em, nosep}`). But this doesn't work for lists defined in `markdown`. As mentioned in #2, `markdown` uses `paralist compactitem` to render lists, is this right? Is it possible to use `enumitem` for lists defiend in `markdown`? Thanks.

The `paralist` package is only loaded when the [`tightLists`][tightLists] option is set to `true`, see also [Section 3.3.4 of the technical documentation][section-3.3.4]:

> > If the \markdownOptionTightLists macro expands to false, do not load the paralist package. This is necessary for LaTeX2ε document classes that do not play nice with paralist, such as beamer. […]

Therefore, the easiest way out for you should be the following:

```latex
\markdownSetup{
    tightLists = false,
}
```

 [section-3.3.4]: http://mirrors.ctan.org/macros/generic/markdown/markdown.pdf#page=147
 [tightLists]: http://mirrors.ctan.org/macros/generic/markdown/markdown.html#option-tightlists

**Comment by Witiko** [comment]
> Another question: how can I use `hyperref` for links?

One possible way would using [the link renderer][link-renderer]:

```latex
\markdownSetup{
    renderers = {
        link = {\href{#3}{#1}},
    },
}
```

 [link-renderer]: http://mirrors.ctan.org/macros/generic/markdown/markdown.html#link-renderer

**Comment by lululxvi** [comment]
Thank you. `tightLists=false` works. I have a few other questions:
- What grammar of `markdown` can I use? Is it `pandoc`?
- For the link, my previous question is not clear. For example, in latex after importing `hyperref`, we can use \url{google.com} to have nice color and clickable link. How can I do this for url in `markdown`?
- How can comment in `markdown`? I found that `<!--  -->` or `pandoc` style `$--` does not work. Although we can use latex comment grammar `%`, I prefer pure markdown grammar.

Sorry that I have so many questions, because I like this tool, and want to use it extensively. Thank you in advance.

**Comment by Witiko** [comment]
> What grammar of markdown can I use? Is it pandoc? For example, how can I type textsuperscript etc?

We support some of the Pandoc's syntax extensions, namely [citations][] and [tables][]. For the full list of supported syntax extensions, see [Section 2.2 (Options) of the user manual][options].

 [citations]: http://mirrors.ctan.org/macros/generic/markdown/markdown.html#option-citations
 [tables]: http://mirrors.ctan.org/macros/generic/markdown/markdown.html#pipe-tables
 [options]: http://mirrors.ctan.org/macros/generic/markdown/markdown.html#options

**Comment by Witiko** [comment]
> For the link, my previous question is not clear. For example, in latex after importing hyperref, we can use \url{google.com} to have nice color and clickable link. How can I do this for url in markdown?

In markdown, there are [several][links] [ways][automatic-links] of producing links:

```latex
\documentclass{article}
\usepackage{markdown}
\markdownSetup{
    renderers = {
        link = {\href{#3}{#1}},
    },
}
\usepackage{hyperref}
\begin{document}
\begin{markdown}
This is [an example](http://example.com/ "Title") inline link.

[This link](http://example.net/) has no title attribute.

This is [an example] [id] reference-style link.

[id]: http://example.com/  "Optional Title Here"

This is an automatic link: <http://example.com/>.
\end{markdown}
\end{document}
```

The result:

![links](https://user-images.githubusercontent.com/603082/83122270-aa10e900-a0d3-11ea-8166-e9cb7c269b8a.png)

 [automatic-links]: https://daringfireball.net/projects/markdown/syntax#autolink
 [links]: https://daringfireball.net/projects/markdown/syntax#link

**Comment by Witiko** [comment]
> How can comment in markdown? I found that `<!-- -->` or pandoc style `$--` does not work. Although we can use latex comment grammar `%`, I prefer pure markdown grammar.

You can use the [`html` option][html]:

```latex
\usepackage[html]{markdown}
...
\begin{markdown}
This is some text <!-- and this is a comment -->
\end{markdown}
```

 [html]: http://mirrors.ctan.org/macros/generic/markdown/markdown.html#option-html

**Comment by Witiko** [comment]
> I use `iftoggle` from `etoolbox`. Even if I use `\usepackage[hybrid]{markdown}`, the `iftoggle` doesn't work in markdown. Is it as excepted?

It should not be excepted. Can you give an example document?

**Comment by lululxvi** [comment]
Thanks. `iftoggle` actually works. But html `<sup> </sup>` or pandoc `^^` doesn't work for text superscript.

**Comment by Witiko** [comment]
That's correct. HTML is currently just discarded, not rendered, although there are multiple ways we could take HTML support:

1. Support rendering HTML tags such as `<sup>`.
2. Support passing HTML through when typesetting HTML documents using [make4ht](https://github.com/michal-h21/make4ht).

Pandoc's extension for superscripts is currently not supported, but it would be a straightforward addition much like strikeout. I'll make this issue into a feature request and see if I or some other contributor can find the time.

**Comment by TomBener** [comment]
> > For the link, my previous question is not clear. For example, in latex after importing `hyperref`, we can use `\url{google.com}` to have nice color and clickable link. How can I do this for url in `markdown`?
> 
> In markdown, there are [several](https://daringfireball.net/projects/markdown/syntax#link) [ways](https://daringfireball.net/projects/markdown/syntax#autolink) of producing links:
> 
> ```
> \documentclass{article}
> \usepackage{markdown}
> \markdownSetup{
>     renderers = {
>         link = {\href{#3}{#1}},
>     },
> }
> \usepackage{hyperref}
> \begin{document}
> \begin{markdown}
> This is [an example](http://example.com/ "Title") inline link.
> 
> [This link](http://example.net/) has no title attribute.
> 
> This is [an example] [id] reference-style link.
> 
> [id]: http://example.com/  "Optional Title Here"
> 
> This is an automatic link: <http://example.com/>.
> \end{markdown}
> \end{document}
> ```
> 
> The result:
> 
> ![links](https://user-images.githubusercontent.com/603082/83122270-aa10e900-a0d3-11ea-8166-e9cb7c269b8a.png)

If the option `hybrid = true`, the example below with special symbols reported errors:
```tex
\documentclass{article}
\usepackage{markdown}
\markdownSetup{
    hybrid = true,
    renderers = {
        link = {\href{#3}{#1}},
    },
}
\usepackage{hyperref}
\begin{document}
\begin{markdown}

A link with special symbols: <http://www.moa.gov.cn/gk/zcfg/nybgz/201111/t20111122_2414394.htm>

\end{markdown}
\end{document}
```

The errors info was `Missing $ inserted.`, and the log file showed:
```
[]\TU/lmr/m/n/10 A link with special symbols: http://www.moa.gov.cn/gk/zcfg/nybgz/201111/t20111122$[]\OT1/cmr/m/n/10 414394\OML/cmm/m/it/10 :htm[]$ 
 []
```

I know a short link can be applied to fix the issue, bu how can I use both the `hybrid = true` and the original link with special symbols? Thank you!

**Comment by Witiko** [comment]
@TomBener Hello! Try substituting `#3` with `#2` in the definition of link. From [the documentation](http://mirrors.ctan.org/macros/generic/markdown/markdown.html#link-renderer) (emphasis mine):

> The `\markdownRendererLink` macro represents a hyperlink. It receives four arguments: the label, *the fully escaped uri that can be directly typeset, the raw uri that can be used outside typesetting*, and the title of the link.

**Comment by Witiko** [comment]
Closed for inactivity.
