### ISSUE TITLE
No way to adjust the location of the table caption

### ISSUE THREAD

**Issue by juniuspan** [Witiko/markdown#64]
Dear author,

Is there any possibility to adjust the position of the table caption, like above the table? 
As we know, many journals require the captions be placed above the table, I personally consider it necessary to provide an option to let users choose the right position of the caption.

Anyway, thanks for providing such a wonderful tool.

Jun

**Comment by Witiko** [comment]
Dear @juniuspan,

you can use [standard LaTeX packages](https://tex.stackexchange.com/a/22754/70941) to adjust the location of table captions:

```latex
\documentclass{article}
\usepackage{markdown}
\usepackage{float}
\floatstyle{plaintop}
\restylefloat{table}
\usepackage[tableposition=top]{caption}
\begin{document}
\begin{markdown*}{pipeTables, tableCaptions}
| Right | Left | Default | Center |
|------:|:-----|---------|:------:|
|   12  |  12  |    12   |    12  |
|  123  |  123 |   123   |   123  |
|    1  |    1 |     1   |     1  |

  : Demonstration of pipe table syntax.
\end{markdown*}
\end{document}
```

![table-caption](https://user-images.githubusercontent.com/603082/85227244-898b3480-b3dc-11ea-9733-52758f2df542.png)

Alternatively, you can redefine [the default table LaTeX renderer](http://mirrors.nic.cz/tex-archive/macros/generic/markdown/markdown.pdf#page=155).

**Comment by juniuspan** [comment]
> Dear @juniuspan,
> 
> you can use [standard LaTeX packages](https://tex.stackexchange.com/a/22754/70941) to adjust the location of table captions:
> 
> ```
> \documentclass{article}
> \usepackage{markdown}
> \usepackage{float}
> \floatstyle{plaintop}
> \restylefloat{table}
> \usepackage[tableposition=top]{caption}
> \begin{document}
> \begin{markdown*}{pipeTables, tableCaptions}
> | Right | Left | Default | Center |
> |------:|:-----|---------|:------:|
> |   12  |  12  |    12   |    12  |
> |  123  |  123 |   123   |   123  |
> |    1  |    1 |     1   |     1  |
> 
>   : Demonstration of pipe table syntax.
> \end{markdown*}
> \end{document}
> ```
> 
> ![table-caption](https://user-images.githubusercontent.com/603082/85227244-898b3480-b3dc-11ea-9733-52758f2df542.png)
> 
> Alternatively, you can redefine [the default table LaTeX renderer](http://mirrors.ctan.org/macros/generic/markdown/markdown.pdf#page=155).
> 
> In general, the `markdown` package only takes responsibility for the conversion, not the formatting. Therefore, I am not in favor of adding formatting options.

Thanks for the kindness @Witiko , the codes work like a charm now!

**Comment by Witiko** [comment]
Glad I can help. Do not hesitate to ask if you had any other questions.
