### ISSUE TITLE
Prevent escaping latex specific chars within codespan 

### ISSUE THREAD

**Issue by V3lop5** [Witiko/markdown#65]
Hello there,

I found this helpful package to include my generated Java/Kotlin-Doc to Latex. 

```
### Extensions for kotlin.Int

#### length

`fun Int.length(): Int`

Ermittelt die Ziffernanzahl des Integers.
Vorzeichen werden nicht beachtet.
```

compiles to

![image](https://user-images.githubusercontent.com/44635962/85206439-73b93900-b322-11ea-92e0-2a520e643b7c.png)

For the code span I'm using a custom color scheme for the package minted mapped to the command `\kotlin`.

Markdown config:
```
\usepackage[smartEllipses, fencedCode, html]{markdown}
\markdownSetup{
  renderers = {
    emphasis = {{#1}},
    strongEmphasis = {\emph{#1}},
    headingOne = {\vspace{1cm}\textbf{\LARGE#1}},
    headingTwo = #1,
    headingThree = {\textbf{\Large#1}},
    headingFour = {\vspace{0.2cm}\textbf{#1}},
    headingFive = #1,
    headingSix = {\underline{#1}},
    codeSpan = {\kotlin{#1}}
  },
}
```

This workes great so far.

Now I have some constants and methods containing Latex specific chars:

```
#### asString

`fun <T> Iterable<T>.asString(prefix: String = "", toString: (T) -> String = { it.toString() }): String`
```

compiles to markdown

```
\markdownRendererInterblockSeparator
{}\markdownRendererHeadingFour{asString}\markdownRendererInterblockSeparator
{}\markdownRendererCodeSpan{fun <T> Iterable<T>.asString(prefix: String = "", toString: (T) -> String = \markdownRendererLeftBrace{} it.toString() \markdownRendererRightBrace{}): String}\markdownRendererInterblockSeparator
```

and displays as

![image](https://user-images.githubusercontent.com/44635962/85206547-43be6580-b323-11ea-9fa6-66829b91110f.png)

Is there any way to prevent Markdown from escaping latex specific characters within codespans?
I already searched the internet and found no soloutin for my problem. I tried replacing the escaped chars back to the original chars but it went horribly wrong.

I found this Document on the internet:  http://mirrors.ibiblio.org/CTAN/macros/generic/markdown/markdown.pdf
On page 94 the function `write->code` is definied and seems to escape the characters. Is there any way to overwrite this function? 

I appreciate any help.

**Comment by Witiko** [comment]
Hello, @V3lop5. [The `codeSpan` renderer](http://mirrors.ctan.org/macros/generic/markdown/markdown.html#code-span-renderer) receives escaped text, which can be directly fed to `\texttt` and similar TeX commands. If you want the text unescaped, consider using [the `fencedCode` option](http://mirrors.ctan.org/macros/generic/markdown/markdown.html#option-fencedcode) and [the `inputFencedCode` renderer](http://mirrors.ctan.org/macros/generic/markdown/markdown.html#code-block-renderers), which receives a filename of a file containing the unescaped text:

`````tex
\documentclass{article}
\usepackage[fencedCode]{markdown}
\usepackage{fancyvrb}
\markdownSetup{
  renderers = {
    inputFencedCode = {%
      \VerbatimInput{#1}%
    }
  }
}
\begin{document}
\begin{markdown}
#### asString
``` kotlin
fun <T> Iterable<T>.asString(prefix: String = "", toString: (T) -> String = { it.toString() }): String
```
\end{markdown}
\end{document}
`````
In the above example, replace `\VerbatimInput{#1}` with a corresponding command such as `\inputminted{kotlin}{#1}`.

**Comment by V3lop5** [comment]
Thanks alot for helping me out!

Your suggested solution works for me.
