### ISSUE TITLE
Doesn't work with svg package

### ISSUE THREAD

**Issue by hacker-DOM** [Witiko/markdown#66]
Input:
```
\documentclass{article}

\usepackage{markdown}
\usepackage{svg}
\begin{document}
a
\end{document}
```

Expected output: `a`
Received: gibberish

Also see same issue on [svg](https://github.com/mrpiggi/svg/issues/28)

**Comment by hacker-DOM** [comment]
Enountered on Overleaf with poth Lualatex and pdflatex.

**Comment by mrpiggi** [comment]
The problem arises from an incompatibility between `pgfrcs' and `svg'...

**Comment by mrpiggi** [comment]
...or more specific with package `transparent` and any package which includes `pgfutil-common.tex` in an improper way like `pgfrcs`, see https://github.com/ho-tex/transparent/issues/3. This issue can be closed as package `svg` provides a fix for package `transparent` although it should be fixed there...

**Comment by Witiko** [comment]
It seems that this issue is not related to the Markdown package, so I am closing it. Please, feel free to reopen if you feel as though this is not the case.

**Comment by mrpiggi** [comment]
Well, you didn't close it ;)

**Comment by Witiko** [comment]
Done and done. 😉
