### ISSUE TITLE
Add citation style file.

### ISSUE THREAD

**Issue by guifsdev** [Witiko/markdown#67]
First of all, I would like to say thank you to everyone involved in this amazing project.

I'm sorry if this is already implemented. I couldn't locate in the docs.
I would like to use ABNT as a citation style in my document. Normally I would include a `.csl` file in the metadata section of the markdown file I'm editing. Is it somehow possible to do with this package?

**Comment by Witiko** [comment]
Hello,

no, using the Citation Style Language is currently not supported. All citation styling is controlled by LaTeX. i.e. using BibTeX, BibLaTeX, or NatBib.

**Comment by guifsdev** [comment]
@Witiko Thank you very much for the clarification. I'll be looking forward for this feature.

**Comment by zepinglee** [comment]
> If there ever exists support for the CSL in LaTeX, I should be able to add it to the markdown package easily. However, [that's not the case at the moment](https://tex.stackexchange.com/a/69284/70941).

I'm currently working on `https://github.com/zepinglee/citeproc-lua` which is aimed to provide CSL support for LaTeX. It will be published to CTAN soon.
