### ISSUE TITLE
Add support for finalizing and freezing the cache

### ISSUE THREAD

**Issue by Witiko** [Witiko/markdown#68]
[The `minted` package supports the `finalizecache` and `frozencache` options](http://mirrors.ctan.org/macros/latex/contrib/minted/minted.pdf#page=12), which allow the user to finalize the cache, and to typeset the cache without accessing the system's shell, respectively. This is useful for baking the outputs of `minted` into the sources.

_An example use case: A user submits the LaTeX source code of their article to [the arXiv repository](https://arxiv.org/), where the source code is automatically typeset just by invoking `pdflatex` without accessing the system's shell or invoking external programs._

It would be useful if similar options could be added to the `markdown` package. Maintaining the naming will make it possible to control the behavior of both the `minted` package and the `markdown` package at the same time, which is convenient for the user.

**Comment by krono** [comment]
That'd be great!

**Comment by Witiko** [comment]
Hopefully, this will make publishing papers with `markdown` less painful.  
You can track the progress in pull request #69.

**Comment by Witiko** [comment]
The issue was closed in 24bd6fc8650324a090da92b438718dedc3d3ac96. This is a new section from the user manual discussing finalizing and freezing the cache, which will be published with the next release.

#### Finalizing and Freezing the Cache

The **`\markdownOptionFrozenCache`** option uses the mapping previously created by the Lua interface **finalizeCache** option, and uses it to typeset the plain TeX document without invoking Lua. As a result, the plain TeX document becomes more portable, but further changes in the order and the content of markdown documents will not be reflected. It defaults to `false`.

The standard usage of the **finalizeCache** and **`\markdownOptionFrozenCache`** options is as follows:

1. Remove the **cacheDir** cache directory with stale auxiliary cache files.
2. Enable the **finalizeCache** option.
3. Typeset the plain TeX document to populate and finalize the cache.
4. Enable the **`\markdownOptionFrozenCache`** option.
5. Publish the source code of the plain TeX document and the **cacheDir** directory.

For more information, see the examples for the **finalizeCache** option.
