### ISSUE TITLE
Issue with markdown containing latex identifiers/special characters (?)

### ISSUE THREAD

**Issue by SirWindfield** [Witiko/markdown#70]
---
Please see second comment for the problem that caused this issue!
---
Hey!
First off, thanks for creating this package! I am really new to Latex and maybe I am just doing something wrong :)

I have some piece of text that I want to automatically change its fontsize, the piece of text being markdown that gets rendered using your package. The piece of code that scales the fontsize is taken from https://tex.stackexchange.com/questions/26002/fit-text-into-given-box-by-adjusting-the-fontsize (I added it below as well).

I think the issue is a combination of this package and the `fitbox` environment from the answer. The text contains stuff like `\emph` after being expanded and the compiler errors out during compilation (error provided below). My guess would be that the fitbox is either not meant to be used with latex input or the markdown package is being used incorrectly here.

The error only occurs when actual markdown syntax is present in the piece of text, which strengthens my assumption above.

Any tips/help you can give me if the error is related to this crate? :)
Cheers!

<details><summary>Expand for code</summary>
Code:

```latex
\makeatletter
\NewEnviron{fitbox}[2]{% \begin{fitbox}{<width>}{<height>} stuff \end{fitbox}
  \def\buildbox{%
    \setbox0\vbox{\hbox{\minipage{#1}%
      \fontsize{\fontdim}{1.2\fontdim}%
      \selectfont%
      \stuff%
    \endminipage}}%
    \dimen@\ht0
    \advance\dimen@\dp0
  }
  \def\stuff{\BODY}% Store environment body
  \buildbox
  % Compute upper and lower bounds
  \ifdim\dimen@>#2
    \loop
      \fontdim.5\fontdim % Reduce font size by half
      \buildbox
    \ifdim\dimen@>#2 \repeat
    \lowerfontdim\fontdim
    \upperfontdim2\fontdim
    \fontdim1.5\fontdim
  \else
    \loop
      \fontdim2\fontdim % Double font size
      \buildbox
    \ifdim\dimen@<#2 \repeat
    \upperfontdim\fontdim
    \lowerfontdim.5\fontdim
    \fontdim.75\fontdim
  \fi
  % Now try to find the optimum size
  \loop
    %\message{Bounds: \the\lowerfontdim\space
    %         \the\fontdim\space \the\upperfontdim^^J}
    \buildbox
    \ifdim\dimen@>#2
      \moreiterationstrue
      \upperfontdim\fontdim
      \advance\fontdim\lowerfontdim
      \fontdim.5\fontdim
    \else
      \advance\dimen@-#2
      \ifdim\dimen@<10pt
        \lowerfontdim\fontdim
        \advance\fontdim\upperfontdim
        \fontdim.5\fontdim
        \dimen@\upperfontdim
        \advance\dimen@-\lowerfontdim
        \ifdim\dimen@<.2pt
          \moreiterationsfalse
        \else
          \moreiterationstrue
        \fi
      \else
        \moreiterationsfalse
      \fi
    \fi
  \ifmoreiterations \repeat
  \box0% Typeset content
}
\makeatother
```
</details>
<details><summary>Expand for error message</summary>
! Missing $ inserted.
<inserted text> 
                $
l.32     \end{fitbox}
</details>

**Comment by SirWindfield** [comment]
After some more testing I discovered that the problem occurs when defining markdown using the environment `markdown` and using double-underscore for bold `--`:

```tex
\begin{markdown}
This is some __bold__ text.
\end{markdown}
```

The issue is that `_` needs to be escaped inside of Latex. Escaping it using `\_` does compile now successfully. However, the output isn't bold. The output would be `This is some __bolt__ text` in this case.

**Comment by Witiko** [comment]
Hi, I don't see any markdown in the code you included in the original post. Can you please share the part, where you use the markdown package, or the full code?

**Comment by SirWindfield** [comment]
Oh, I totally forgot that one!

I used the above `fitbox` environment in this snippet:
```tex
\begin{fitbox}{\textwidth}{4cm}
	\begin{markdown}
	Some markdown using the **bold** pattern, which doesn't work on my machine.
	\end{markdown}
\end{fitbox}
```

**Comment by Witiko** [comment]
The `markdown` environment is a little like the `verbatim` environment: it does not like being passed around in arguments to other commands. Can you try the following code and see if this fixes you issue?

``` sh
\begin{markdown}
\begin{fitbox}{\textwidth}{4cm}
	Some markdown using the **bold** pattern, which doesn't work on my machine.
\end{fitbox}
\end{markdown}
```

**Comment by Witiko** [comment]
I am closing this issue due to a month of reactivity. Please, feel free to reopen if you're experience this issue.

**Comment by SirWindfield** [comment]
No worries, thanks for the help. I couldn't come around and test it. If it doesn't work, I'll re-open :)
