### ISSUE TITLE
How to use multiple citations as a unified subjective of a sentence?

### ISSUE THREAD

**Issue by TomBener** [Witiko/markdown#71]
I have a sentence where 3 citekeys were inserted as the subjective, the expected output should be:

```
Coser (1956, 1957, 1967) argues that conflict can serve a positive role for the social relationship and social structure…
```

And the BibTeX file contents:

```
@book{coser1956,
  title = {The {{Functions}} of {{Social Conflict}}},
  author = {Coser, Lewis A.},
  year = {1956},
  pages = {188},
  publisher = {{The Free Press}},
  address = {{New York}},
  series = {The Functions of Social Conflict}
}

@article{coser1957,
  title = {Social {{Conflict}} and the {{Theory}} of {{Social Change}}},
  author = {Coser, Lewis A.},
  year = {1957},
  volume = {8},
  pages = {197--207},
  publisher = {{[Wiley, London School of Economics and Political Science, London School of Economics]}},
  doi = {10.2307/586859},
  journal = {The British Journal of Sociology},
  number = {3}
}

@book{coser1967,
  title = {Continuities in the Study of Social Conflict},
  author = {Coser, Lewis A.},
  year = {1967},
  pages = {x, 272},
  publisher = {{The Free Press}},
  address = {{New York}},
  series = {Continuities in the Study of Social Conflict}
}
```

I know the `hybrid` mode can be turned on to write raw LaTeX command in Markdown files like `\citep{coser1956, coser1957, coser1967}`, which renders the ideal result like above.

However, the raw LaTeX command cannot be processed correctly when converting `.md` to `.docx` with Pandoc. So I'd like to know if it’s possible to write native Markdown citekeys like `@coser1956` for multiple citations as a unified subjective of a sentence (no parentheses)?

I have tried:

```
 @coser1956 -@coser1957 -@coser1967 argues that conflict can serve a positive role for the social relationship and social structure…
```
But it rendered:

```
Coser (1956) (1957) (1967) argues that conflict can serve a positive role for the social relationship and social structure…
```
Not the expected:

```
Coser (1956, 1957, 1967) argues that conflict can serve a positive role for the social relationship and social structure…
```

Or could you please provide other solutions for this issue? Thank you 😊

**Comment by TomBener** [comment]
The Author of Pandoc [replied](https://github.com/jgm/citeproc/issues/42#issuecomment-751391625) this can be achieved like this:

```
@coser1956 [@coser1957; @coser1967]
```

But this syntax cannot be parsed by this package. Could markdown package support this kind of citation?

**Comment by Witiko** [comment]
@TomBener Hello. We currently do not support the above syntax, since it does not allow you to mark up a text citation followed by two parenthetical citations. We support the following syntax:

- `@x1992 [@x1993; @x1994]` becomes `X (1992) (X, 1993; X, 1994)`, i.e. a text citation followed by two parenthetical citations.
- `@x1992 [; @x1993; @x1994]` becomes `X (1992, 1993, 1994)`, i.e. a string of three text citations.

**Comment by TomBener** [comment]
Wow, that's perfect!

The latter is what I really need, which is available for Pandoc when converting to `.docx`.

Really useful, thanks for your kind reply!

**Comment by Witiko** [comment]
@TomBener Glad I could help. We also support the following syntax:

3. `@x1992 @x1993 @x1994` becomes `X (1992) X (1993) X (1994)`, i.e. three separate text citations.

I would be in favor of unifying the meaning of 2 and 3, since 3 is arguably the most intuitive way to mark up three text citations.

**Comment by TomBener** [comment]
Very insightful view.

The 2 is the format that my institution requires, so I have to make the citation like that 😂

By the way, is it possible to support cross reference for table and figure using [pandoc-crossref](https://github.com/lierdakil/pandoc-crossref). If so, it would be completely perfect for academic writing with this package.

**Comment by Witiko** [comment]
> Very insightful view!
> 
> The 2 is the format that my institution requires, so I have to make the citation like that joy

The idea is that you could write either `@x1992 [; @x1993; @x1994]` or `@x1992 @x1993 @x1994`, and have it become `X (1992, 1993, 1994)`. I have drafted an implementation of this idea in 8c7168375892edbdcc1b306274574c102f310eea.

> By the way, is it possible to support cross reference for table and figure using [pandoc-crossref](https://github.com/lierdakil/pandoc-crossref)? If so, it would be completely perfect for academic writing with this package.

Not at the moment. Currently, we provide limited support for adding id attributes to sections for the purpose of [content slicing](https://www.tug.org/TUGboat/tb40-1/tb124novotny-markdown.pdf#page=3).

**Comment by TomBener** [comment]
Thanks for your work!

**Comment by Witiko** [comment]
No problem. @drehak is planning to add support for invoking Pandoc directly from the Markdown package, so using [pandoc-crossref](https://github.com/lierdakil/pandoc-crossref) may become a possibility in the course of the next year.
