### ISSUE TITLE
underscores in equations get interpreted into emphasis

### ISSUE THREAD

**Issue by wang1zhen** [Witiko/markdown#73]
issue: in my markdown file, there's only a single line of the equation:
```markdown
$$
A_a \Rightarrow B_b
$$
```
when I try to include this file with `\markdownInput{a.md}`, the build failed, and the file generated suggests that the underscores were regarded as emphasis:
```tex
$$ A\markdownRendererEmphasis{a \Rightarrow B}b $$\relax
```

it is strange that if I try anything like `A_aB_bC_cD_d` in the equation, everything's fine, but if there is a `\Rightarrow`, or `\uparrow`, `\leftarrow` between the underscores, it breaks.

**Comment by wang1zhen** [comment]
`\frac` also breaks it, which could be reproduced by `a_1=\frac{b_1}{2}`

**Comment by Witiko** [comment]
The markdown package does not parse math. If you want to use underscores in math equations, you can either escape the underscores (`\_`), disable the special meaning of underscores globally or locally (`\markdownSetup{underscores=false}`), or jump out of markdown temporarily (`\end{markdown}`).

**Comment by wang1zhen** [comment]
Thank you! It was my fault to consider that the underscores in the between-line equations would be parsed. Setting `\markdownSetup{underscores=false}` is an efficient and elegant way to do so, thanks again for your help!

**Comment by Witiko** [comment]
> Thank you! It was my fault to consider that the underscores in the between-line equations would be parsed. Setting `\markdownSetup{underscores=false}` is an efficient and elegant way to do so, thanks again for your help!

It's an reasonable assumption. Pandoc, for example, recognizes math in the input and special-cases it. Our package is a lot simpler and does not assume much about the extra-markdown markup of the input. This is partly because we also support TeX formats other than LaTeX (plain TeX, ConTeXt, ...), which have a different syntax for math, and partly because TeX is Turing-complete, i.e. detecting which parts of the input are math and which are text is generally undecidable.

**Comment by pdmosses** [comment]
@Witiko I was about to submit a separate issue regarding underscores in math when I noticed your comments on this one. You wrote:

> The markdown package does not parse math. If you want to use underscores in math equations, you can either escape the underscores (`\_`), ...

Here is my test file:

```latex
\documentclass{article}
\usepackage{markdown}
\begin{document}

\begin{markdown*}{hybrid}
$\sqrt{\_}$
\end{markdown*}

\end{document}
```

I get the following error:

```
pdflatex --shell-escape test.tex 
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020) (preloaded format=pdflatex)
 \write18 enabled.
entering extended mode
(./test.tex
LaTeX2e <2020-10-01> patch level 3
L3 programming layer <2020-12-07> xparse <2020-03-03>
(/usr/local/texlive/2020/texmf-dist/tex/latex/base/article.cls
Document Class: article 2020/04/10 v1.4m Standard LaTeX document class
(/usr/local/texlive/2020/texmf-dist/tex/latex/base/size10.clo))
(/usr/local/texlive/2020/texmf-dist/tex/latex/markdown/markdown.sty
...
(/usr/local/texlive/2020/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def)
(./test.aux)
(/usr/local/texlive/2020/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (/usr/local/texlive/2020/texmf-dist/tex/latex/epstopdf-pkg/epstopdf-base.sty
(/usr/local/texlive/2020/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))
(./test.markdown.out (./_markdown_test/ee83349c804364ba4c61c67cee0491cf.md.tex
! Missing { inserted.
<to be read again> 
                   }
l.1 $\sqrt{_}
             $\relax
```

The underscore appears to have been removed from `\_` when writing to the out file.

**Comment by Witiko** [comment]
@pdmosses That's expected behavior. One backslash tells Markdown that it should consider `_` just a character, not a markup of emphasis. You need three backslashes if you want to persist the backslash to the output as a separate character: `\\\_`.

**Comment by pdmosses** [comment]
@Witiko thanks for the quick and helpful response. 

I'm using kramdown to generate web pages; it allows LaTeX markup only inside its [math blocks](https://kramdown.gettalong.org/syntax.html#math-blocks), and special Markdown characters there don't need any escaping (apart from `|`, which apparently might get mistaken for a table column separator). I was hoping that the `hybrid` option of this package would preserve LaTeX markup inside the usual LaTeX delimiters, but now I understand that it doesn't. I'll try using [kramdown's Markdown-to-LaTeX](https://kramdown.gettalong.org/converter/latex.html) converter instead.

**Comment by Witiko** [comment]
> I was hoping that the `hybrid` option of this package would preserve LaTeX markup inside the usual LaTeX delimiters, but now I understand that it doesn't. I'll try using [kramdown's Markdown-to-LaTeX](https://kramdown.gettalong.org/converter/latex.html) converter instead.

The `hybrid` option disables the escaping of plain TeX's special characters, such as `\`, `#`, and `%` in the output. No parsing of the input is performed; https://github.com/Witiko/markdown/issues/73#issuecomment-762246813 discusses why that is.
