### ISSUE TITLE
files referenced in markdown are lost in latex

### ISSUE THREAD

**Issue by pappou99** [Witiko/markdown#76]
When using the markdown package and inserting a markdown file with referenced external files (e.g. pictures) these are lost in the latexfile and placeholders are inserted.

here a mwe:

```
\documentclass[fontsize=10pt,a4paper,final]{scrartcl}
\usepackage{markdown}
\usepackage{lipsum}

\begin{document}
    \section{First}
    \lipsum[22]
    \markdownInput{../other_project/README.md}
    \lipsum[55]
\end{document}
```

The markdownfile is - as you can see - in a subfolder outside of the texfilefolder and looks like:
```
[![Sample picture](./res/sample.png)](https://sample.url)
[![Sample picture](res/sample.png)](https://sample.url)

Sample - An sample Software
=======================================


Sample text sample text sample text sample text sample text sample text sample text sample text
Sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text

```
In the result there are no pngs shown:
[test.pdf](https://github.com/Witiko/markdown/files/6218036/test.pdf)
![Bildschirmfoto von 2021-03-28 22-52-22](https://user-images.githubusercontent.com/28729133/112767660-51262000-9018-11eb-9acd-363afad4c995.png)

markdown package version via texlive 2020

**Comment by Witiko** [comment]
Image paths (`./res/sample.png`) are relative to your LaTeX document, not the included file (`../other_project/README.md`).   
You can tell LaTeX where to look for the images by putting `\graphicspath{ {../other_project} }` in the preamble.

See also:
1. [The folder path to images (Overleaf)][1]
2. [How to use `\graphicspath`? (TeX SE)][2]

 [1]: https://www.overleaf.com/learn/latex/Inserting_Images#The_folder_path_to_images
 [2]: https://tex.stackexchange.com/a/139403/70941

**Comment by Witiko** [comment]
@pappou99 Has this solved your issue? 🙂

**Comment by Witiko** [comment]
I am closing this down due to inactivity. Please, feel free to reopen if you have additional input.
