### ISSUE TITLE
Error in rendering link with percent character

### ISSUE THREAD

**Issue by nopria** [Witiko/markdown#79]
URLs inside link either of type

    [link-label](some-url)

or 

    <some-url>

are not handled correctly if URL contains a percent character, giving the error (I compile with XeLaTeX)

    ! File ended while scanning use of \markdownRendererLink

Since `\url{some-url}` from `xurl` package is able to handle percent char inside URL, I tried defining a custom renderer

    \markdownSetup{ renderers = {link = {\url{#3}}} }

but the error is still there.

**Comment by Witiko** [comment]
Hello. I don't think this can be solved without disabling the the `hybrid` option. The percent sign will be long discarded by the input processor before we even expand `\markdownRendererLink` to `\url`.

You could disable the special meaning of `%` in TeX. This way, you would not be able to use TeX comments, but you would be able to use `%` in your code freely:
``` tex
\begingroup
\catcode`\%=12
\begin{markdown}
\end{markdown}
\endgroup
```

**Comment by nopria** [comment]
I forgot to mention that the problem arises only with `hybrid` option, sorry. I will make other tests to see if your suggestion allow to keep the `hybrid` option.
@Witiko

**Comment by Witiko** [comment]
@nopria I know, the suggested solution should work with the `hybrid` option.

**Comment by Witiko** [comment]
This solution will likely be incorporated directly to the Markdown package, since having the percent sign (`%`) as a comment character in the plain TeX output of the Markdown package has only caused grief and should now be completely unnecessary with the `texComments` Lua option (https://github.com/Witiko/markdown/issues/42#issuecomment-826359071). Thanks for reporting the issue!

**Comment by nopria** [comment]
> This solution will likely be incorporated directly to the Markdown package, since having the percent sign (`%`) as a comment character in the plain TeX output of the Markdown package has only caused grief and should now be completely unnecessary with the `texComments` Lua option ([#42 (comment)](https://github.com/Witiko/markdown/issues/42#issuecomment-826359071)). Thanks for reporting the issue!

I confim that with `\markdownSetup{ renderers = {link = {\url{#2}}} }` your solution works fine, but to avoid errors in  my document I had to change catcode of more characters:

```tex
\catcode`\&=12
\catcode`\_=12
```

I don't know if I can ask you here, but is it possible to use some conditionals in `\markdownSetup` so that `<some-url>` is rendered as `\url{some-url}` but `[some-label](some-url)` keeps the standard rendering? I also started a question about this at https://tex.stackexchange.com/q/599526/28685

**Comment by Witiko** [comment]
> but to avoid errors in my document I had to change catcode of more characters

For these, you can always change the catcodes and use `\tokenize` inside the renderer. Redefining them globally means you lose the ability to use subscripts in math (`_`) and write table separators (`&`) in the `hybrid` mode. However, the comments will have been stripped by the input processor by the time the expansion takes place, so they require a special treatment.

> is it possible to use some conditionals in `\markdownSetup` so that `<some-url>` is rendered as `\url{some-url}` but `[some-label](some-url)` keeps the standard rendering?

Not at the moment, no, but you could add a new renderer such as `\markdownRendererAutolink` that would allow you to handle autolinks differently. You can also detect an autolink by comparing parameters `#1` and `#2` for equality.
