### ISSUE TITLE
Enable internal hyperref references

### ISSUE THREAD

**Issue by nbubis** [Witiko/markdown#87]
It would be great if we could have support for internal references. Right now, this can be achieved by using hybrid mode, and using hyperref, e.g.:

```
\hyperref[sec:mysub]{Link to subsection}

## My Subsection 
\label{sec:mysub}
```

Markdown supports this using HTML anchors, e.g. `<a id="mysub"></a>` and then `[mysub](Link to subsection)`, but this syntax doesn't seem supported yet by the Markdown package.

**Comment by Witiko** [comment]
We already support html attributes. Perhaps we could allow the user to react to these?

``` markdown
[Link to subsection](#sec:mysub)

## My Subsection {#sec:mysub}
```

**Comment by Witiko** [comment]
This issue is a subset of https://github.com/Witiko/markdown/issues/91. Closing.
