### ISSUE TITLE
Pass HTML through to TeX4ht

### ISSUE THREAD

**Issue by Witiko** [Witiko/markdown#90]
Since version [2.3.0][], the Markdown package has supported the `html` Lua option, which makes the Lua parser recognize [display and inline HTML][1]. Since version [2.10.0][], inline HTML comments have been [actionable][2], but other HTML nodes have been removed during the conversion to TeX. In order to enable the conversion from Markdown to HTML using @michal-h21's [make4ht][] without the loss of HTML, as discussed in https://github.com/Witiko/markdown/issues/63#issuecomment-635862686, we should:

- Make all HTML nodes (except block HTML elements) actionable:
    - [x] Add `inlineHtmlTag` renderer that will handle opening, closing, and empty inline HTML tags.
    - [x] Add `inlineHtmlComment` renderer for inline HTML comments.
    - [x] Add `inputBlockHtmlElement` renderer for block HTML elements.
    - [x] Add `inputBlockHtmlComment` renderer for HTML comments that span several paragraphs.
- [x] Make the `inlineHtmlTag` LaTeX renderer prototype produce [the `\HCode` command][3] (see also https://github.com/Witiko/markdown/issues/90#issuecomment-894849448) to pass HTML through to TeX4ht.
- [x] Make the `inputBlockHtmlElement` LaTeX renderer prototype produce the `\special` command (see also https://github.com/Witiko/markdown/issues/90#issuecomment-1036327541) to pass HTML through to TeX4ht.
- [x] Add [an example document][6] for TeX4ht.
- [x] Update [the documentation of the `html` Lua option][5].

We should add these definitions to [markdown.dtx][4], not to the TeX4ht literate sources, since users may completely change the semantics of the HTML nodes by redefining the renderers. In that case, we don't want the renderers to produce `\HCode`.

 [1]: https://github.com/witiko/markdown/blob/2.3.0/markdown.dtx#L3156
 [2]: https://github.com/witiko/markdown/blob/2.10.0/markdown.dtx#L16680
 [3]: https://www.kodymirus.cz/tex4ht-doc/Configurations.html#x8-510007.3.4
 [4]: https://github.com/witiko/markdown/blob/main/markdown.dtx
 [5]: https://witiko.github.io/markdown#option-html
 [6]: https://github.com/witiko/markdown/tree/main/examples

 [make4ht]: https://github.com/michal-h21/make4ht

 [2.3.0]: https://github.com/witiko/markdown/releases/tag/2.3.0
 [2.10.0]: https://github.com/witiko/markdown/releases/tag/2.10.0

**Comment by michal-h21** [comment]
That's a great idea! I already tested the Markdown package with TeX4ht and it works in most cases. I think that I experienced some errors, but I don't remember what was the cause. 

Anyway, regarding passing HTML from Markdown, I think that just `\HCode` isn't sufficient, because it won't correctly close paragraphs. You will need something like this:

```
\documentclass{article}
\ifdefined\HCode
\newcommand\htmlcode[1]{\ifvmode\IgnorePar\EndP\fi\HCode{#1}}
\else
\newcommand\htmlcode[1]{}
\fi
\begin{document}

Hello 

\htmlcode{<div>}\htmlcode{<span>}world\htmlcode{</span>}\htmlcode{</div>}

Text continues, we may also try an \htmlcode{<i>}inline HTML\htmlcode{</i>}.

\end{document}

```

It produces a following HTML with `make4ht`:

```
<!-- l. 9 --><p class='noindent'>Hello
</p>
   <div><span>world</span></div>
<!-- l. 13 --><p class='indent'>   Text continues, we may also try an <i>inline HTML</i>.
</p>
```

Without `\ifvmode\IgnorePar\EndP\fi`, you would get `<p>` around the `<div>` element, which is non-valid in HTML.

**Comment by Witiko** [comment]
@michal-h21 I have added todos for this issue (see https://github.com/Witiko/markdown/issues/90#issue-963464425) and I plan to tackle them by the end of the month.

I have a couple of concerns:

- Adding a renderer for inline HTML seems simple enough. However, for multi-paragraph block elements, it may be easier to pass it around in an auxiliary file, which would be appended as-is to the output and which would not be subject to expansion. Is there any such mechanism in TeX4ht? Otherwise, it may be practical to only support inline HTML for the moment.

- Since TeX4ht is not a format, it does not make much sense to include it in [unit tests][1]. However, it would be useful to have [an example document][2] for make4ht and I would appreciate review of the example document that I come up with, since I feel quite new to TeX4ht. In the long run, we may want to convert [the user manual][3] from Pandoc to TeX4ht, so that we are fully self-sufficient.

 [1]: https://github.com/Witiko/markdown/tree/main/tests/templates
 [2]: https://github.com/Witiko/markdown/tree/main/examples
 [3]: https://witiko.github.io/markdown/

**Comment by michal-h21** [comment]
@Witiko yes, it is possible to input contents of HTML file, using the `\special` command. There is still a issue with paragraphs. They need to be closed before inputting the HTML snippet, and then opened after. 

The following code shows the concept:

```
\documentclass{article}
\begin{document}

This is text from the TeX file

\ifvmode\IgnorePar\fi\EndP
\special{t4ht*<hello.html}
\par\ShowPar

Here continues text from the TeX file
\end{document}
```
The `\ifvmode\IgnorePar\fi\EndP` is needed to close the paragraph,  and `\par\ShowPar` opens paragraph after the inputed file. `\special{t4ht*<filename} includes the file.

I can surely help with the example.

**Comment by Witiko** [comment]
@michal-h21 In b00280b, I added an example document. The good news is that the HTML pass-through works as expected:

``` md
Here is some <b>HTML code</b> mixed *with Markdown*. In pdfTeX, the HTML code
will be silently ignored, whereas in \TeX 4ht, the HTML code will be passed
through to the output:

<table border="1">
  <tr>
    <td>Emil</td>
    <td>Tobias</td>
    <td>Linus</td>
  </tr>
  <tr>
    <td>16</td>
    <td>14</td>
    <td>10</td>
  </tr>
</table>
```

![output of the above code](https://user-images.githubusercontent.com/603082/155904839-7c67c437-2158-4131-8b79-53ae7e0b940e.png)

- [latex-tex4ht.html](https://github.com/Witiko/markdown/files/8149653/latex-tex4ht.html.txt)
- [latex-tex4ht.css](https://github.com/Witiko/markdown/files/8149652/latex-tex4ht.css.txt)

**Comment by Witiko** [comment]
The bad news is that with up-to-date TeX Live 2021, the compilation produces a number of errors that seem pretty arcane to me:

![Untitled](https://user-images.githubusercontent.com/603082/155904897-d1792296-3077-42d4-bb1d-1959794c302c.png)

To see what was going on, I ran the following command. The error log indicates that at some point `\cur:rule` is not defined, but I did not dig deeper.

```
$ htlatex latex.tex '' "xhtml,html5,mathml,charset=utf-8" " -cunihtf -utf8" -shell-escape
```

![output of the above command](https://user-images.githubusercontent.com/603082/155905024-50fc4937-1d31-4a35-a729-14b7f2b49d6c.png)

Worse yet, make4ht seems to crash our continuous integration with [TeX Live 2018](https://github.com/Witiko/markdown/runs/5353037143) and [2019](https://github.com/Witiko/markdown/runs/5353077585):

```
$ make4ht -m clean latex
Output dir: 	
Compiler: 	latex
Latex options: 	 -jobname=latex 
tex4ht.sty :	xhtml,
tex4ht	
build_file	latex.mk4
Output format	html5
/usr/local/texlive/2018/bin/x86_64-linux/make4ht:62: attempt to index local 'formatter' (a nil value)
```

Since I would like to release today at the latest, I plan to merge commit 44affc3 and ship Markdown 2.14.0 without an example document TeX4ht, which I would merge later when ready. However, if we could get the example document in order today or tomorrow at the latest, we could ship it with Markdown 2.14.0 already.

**Comment by michal-h21** [comment]
@Witiko this issue seems to be caused by tables. `\cur:rule` is used by the TeX4ht configuration for Booktabs, but you will get the underlying error even when you comment out Booktabs in the LaTeX document. 

I think this issue is caused by these lines in `markdown.sty`:

```
\@ifpackageloaded{booktabs}{
  \let\markdownLaTeXTopRule\toprule
  \let\markdownLaTeXMidRule\midrule
  \let\markdownLaTeXBottomRule\bottomrule
}{
  \let\markdownLaTeXTopRule\hline
  \let\markdownLaTeXMidRule\hline
  \let\markdownLaTeXBottomRule\hline
}
```

As TeX4ht overwrites `\hline`, `\toprule`, and the rest of the table rule commands with code that inserts HTML code, you get an error when you save their unpatched versions in `\markdownLaTeXTopRule` etc. Simply using `\AtBeginDocument` around this code block seems to fix this. It has also the advantage that it will support Booktabs loaded after the Markdown package.

**Comment by Witiko** [comment]
Always a pleasure to see someone more capable at work! I added `\AtBeginDocument` as suggested and replaced `\let` with `\def` for further robustness in 03a444a. A quick search shows that [`make4ht` won't work in TeX Live 2018 and 2019](https://www.mail-archive.com/xetex@tug.org/msg11083.html), so I replaced your `make4ht` command with `htlatex` in the Makefile in [67a5830](https://github.com/Witiko/markdown/commit/67a5830c3b61ad30f4190a20fb4edb33850ee2d1), but mentioned the corresponding make4ht command in a comment. As soon as we have lost support for TeX Live 2018 and 2019, we can replace `htlatex` with `make4ht`.

**Comment by Witiko** [comment]
The example document seems passable except for the imbalanced `<center>` tag that we can see already in the output of `make4ht` in https://github.com/Witiko/markdown/issues/90#issuecomment-1053728817 and which causes all the text below the blockquote to be centered:

``` md
> This is the first level of quoting.
>
> > This is nested blockquote.
>
> Back to the first level.
```
``` html
   <div class="center-quotation"><table class="quotation" 
border="0" cellpadding="0" cellspacing="15"><tr><td> 
        <blockquote class="quotation">
     <!--l. 87--><p class="indent" >     This is the ﬁrst level of quoting.
</p>
        <div class="center-quotation"><table class="quotation" 
border="0" cellpadding="0" cellspacing="15"><tr><td> 
       <blockquote class="quotation">
    <!--l. 89--><p class="indent" >     This is nested blockquote.</p></blockquote>
     </td></tr></table></center>
        Back to the ﬁrst level.</blockquote>
</td></tr></table></center>
```

![image of the above code](https://user-images.githubusercontent.com/603082/155976939-b2ea6e32-dfa3-43b3-b651-8400a1e2d2df.png)

It seems like TeX4ht should close the opening `<div class="center-quotation">` with a closing `</div>` rather than `</center>`.

**Comment by michal-h21** [comment]
@Witiko this is strange, it shouldn't produce any `<table class="quotation">`, we use just `<blockquote>` for quotations. And the sample from your previous message produces this on my system:
```
        <blockquote class='quotation'>
     <!-- l. 3 --><p class='noindent'>This is the first level of quoting.
       </p><blockquote class='quotation'>
    <!-- l. 5 --><p class='indent'>     This is nested blockquote.</p></blockquote>
     <!-- l. 7 --><p class='indent'>     Back to the first level.</p></blockquote>
```

**Comment by Witiko** [comment]
@michal-h21 Interesting. I have the following minimal example document `example.tex`:

``` tex
\documentclass{article}
\usepackage{markdown}
\begin{document}
\begin{markdown}

> This is the first level of quoting.
>
> > This is nested blockquote.
>
> Back to the first level.

\end{markdown}
\end{document}
```

Running `htlatex example "xhtml,fn-in,html5,charset=utf-8" " -cunihtf -utf8" '' -shell-escape` or `make4ht --shell-escape example fn-in` produces the following output with up-to-date TeX Live 2021:

``` html
   <div class="center-quotation"><table class="quotation" 
border="0" cellpadding="0" cellspacing="15"><tr><td> 
        <blockquote class="quotation">
     <!--l. 3--><p class="indent" >    This is the ﬁrst level of quoting.
</p>
        <div class="center-quotation"><table class="quotation" 
border="0" cellpadding="0" cellspacing="15"><tr><td> 
       <blockquote class="quotation">
    <!--l. 5--><p class="indent" >    This is nested blockquote.</p></blockquote>
     </td></tr></table></center>
        Back to the ﬁrst level.</blockquote>
</td></tr></table></center>
```

**Comment by michal-h21** [comment]
I've found that this happens with the `amsmath` package for me. It seems to come from the configuration for the `aligned` environment. I need to investigate it a bit, but it seems like a bug on TeX4ht side.

**Comment by Witiko** [comment]
Thank you. In that case, I think we can merge and release this branch.

**Comment by michal-h21** [comment]
I hope so. I've already found the cause of the HTML validation error, but I am still not sure why we execute this code when Amsmath is loaded.

**Comment by michal-h21** [comment]
I've found also the underlying issue, there was some line that configured `quotation` as if it was a math environment when Amsmath is loaded. I've fixed that in TeX4ht sources.

**Comment by Witiko** [comment]
For future reference, the issue has been fixed in revisions [1085](https://svn.gnu.org.ua/viewvc/tex4ht?view=revision&revision=1085) and [1086](https://svn.gnu.org.ua/viewvc/tex4ht?view=revision&revision=1086) of TeX4ht.
